In [1]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA

In [2]:
# span = np.array([[1,2,3],[-1,1,1],[1,1,1],[1,1,1]])
# print(span)
# A1 = span

In [3]:
row = 3
col = 3
span = np.random.randint(10,size=(row,col))
print(span)
A1 = span
A2 = A1

[[5 4 0]
 [1 3 7]
 [5 1 7]]


In [4]:
row,col = span.shape
row

3

In [5]:
# v1 = span[:,0]
# v2 = span[:,1]
# v3 = span[:,2]
# v4 = span[:,3]
# v5 = span[:,4]

In [6]:
# Setup arrays
# Original Values
vector = []
# Normalized Values
vec_norm = []

In [7]:
# First Column

v1 = span[:,0]
vec_1 = v1
print(vec_1)
vector.append(vec_1)

# Test
v1_scale = np.square(np.linalg.norm(vec_1))
print(v1_scale)

v1 = np.multiply(1/np.sqrt(v1_scale),vec_1)
print(v1)
vec_norm.append(v1)


[5 1 5]
51.00000000000001
[0.70014004 0.14002801 0.70014004]


In [8]:
def QR(span): 
    
    # Copy matrix
    A1 = span
    
    # Size of array
    row,col = span.shape
    
    # Setup arrays
    # Original Values
    vector = []
    # Normalized Values
    vec_norm = []
    
    # First Column
    v1 = span[:,0]
    vec_1 = v1
#     print(vec_1)
    vector.append(vec_1)

    # Test
    v1_scale = np.square(np.linalg.norm(vec_1))
#     print(v1_scale)

    v1 = np.multiply(1/np.sqrt(v1_scale),vec_1)
#     print(v1)
    vec_norm.append(v1)     

    # Subsequent Columns

    start = 1
    end = col

    for i in range(start,end):
        
        # Initialize vectors
        length = []
        projection = []
        project = []

        # Columns
        v = span[:,i]

        for i in vector:
            leng = np.dot(i,v)
            length.append(leng)
            proj_0 = np.dot(i,i)
            projection.append(proj_0)
            proj_1 = leng/proj_0
            project.append(proj_1)

#         print(length)
#         print(projection)
#         print(project)
        
        # Factorization
        a = min(projection)
#         print('a:',a)

        # QR equation
        vec_0 = 0
        vec_1 = np.multiply(a,v)
        for i in range(len(vector)):
            vec_0 = vec_0 - np.multiply(project[i]*a,vector[i])

        vect_0 = vec_1 + vec_0    
#         print(vect_0)
        vector.append(vect_0)

        # Scaling vector    
        # Scale
        v_scale = np.square(np.linalg.norm(vect_0))
#         print(v_scale)

        v_norm = np.multiply(1/np.sqrt(v_scale + 1e-15),vect_0)
#         print(v_norm)

        v = v_norm
        vec_norm.append(v_norm)
#         print('v norm:', v_norm)
#         print('\n')
#         print(vector)
#         print('\n')
#         print(vec_norm)
#         print('\n')
#         print(np.array(vec_norm).T)
        
    # Calculate R
    # Q matrix
    Q = np.array(vec_norm)
    # A1 = np.multiply(1,A1)
    R = np.dot(Q,A1)
#     print(R)
    
    return Q.T,R


In [9]:
# Function
Q,R = QR(A1)

In [10]:
print(Q)
print("\n")
print(R)

[[ 0.70014004  0.38494195 -0.60135149]
 [ 0.14002801  0.75183975  0.64430517]
 [ 0.70014004 -0.5353099   0.47249046]]


[[ 7.14142843e+00  3.92078424e+00  5.88117635e+00]
 [-1.88737914e-15  3.25997714e+00  1.51570893e+00]
 [-5.55111512e-17  6.10622664e-16  7.81756939e+00]]


In [11]:
# # Calculate R
# Q = vec_norm
# # A1 = np.multiply(1,A1)
# R = np.dot(Q,A1)
# print(R)

In [12]:

# for _ in range(20):
#     Q,R = QR(A2)
#     Q = np.array(Q)
#     R = np.array(R)
#     A2 = np.dot(Q.T,np.dot(A2,Q))
    
# print(A2)

In [13]:
pQ = np.eye(row)
X = A2
for i in range(100):
        Q,R = QR(X)
        pQ = pQ @ Q
        X = R @ Q
print(np.diag(X))
print(pQ)

[11.06372731  2.06762586  1.86864682]
[[ 0.41277721 -0.83094606 -0.3730196 ]
 [ 0.62574211  0.55629953 -0.54678848]
 [ 0.66186236 -0.00771225  0.74958571]]


In [14]:
w,v = LA.eig(A2)
print(w)
print(v)

[11.06372731+0.j          1.96813634+3.54634907j  1.96813634-3.54634907j]
[[-0.41277721+0.j         -0.38450594-0.44975383j -0.38450594+0.44975383j]
 [-0.62574211+0.j          0.69018842+0.j          0.69018842-0.j        ]
 [-0.66186236+0.j         -0.04681063+0.4139147j  -0.04681063-0.4139147j ]]


In [15]:
B = np.array([[1,2,3],[3,2,1],[1,0,-1]])
B_diag = np.diag(B)


In [16]:
# for _ in range(20):
#     Q,R = QR(B)
#     Q = np.array(Q)
#     R = np.array(R)
#     B = np.dot(R,Q)
# #     B = np.dot(Q.T,np.dot(B,Q))
# B

In [17]:
w,v = np.linalg.eig(B)
w

array([ 4.31662479e+00, -2.31662479e+00,  2.13869201e-17])

In [18]:
# a = np.array([[0, 2], 
#               [2, 3]])
# p = [1, 5, 10, 20]
print(B)
for i in range(20):
    q, r = QR(B)
    q = np.array(q)
    B = np.dot(r,q)
#     B = np.dot(q.T,np.dot(B,q))
#     if i+1 in p:
#         print(f'Iteration {i+1}:')
#         print(A2)
        
A2_diag = np.diag(B)
print(A2_diag)

[[ 1  2  3]
 [ 3  2  1]
 [ 1  0 -1]]
[ 4.3166237 -2.3166237  0.       ]


In [19]:
# C = np.array([[2,1,0],[1,3,1],[0,1,4]])
# C1 = C
# print(C)
# # q,r = QR(C)
# pQ = np.eye(C.shape[1])
# for _ in range(100):
#     q,r = QR(C)
#     pQ = pQ@q
#     C = np.dot(r,q)

# # print(q)

# C_diag = np.diag(C)
# print(C_diag)
# print('\n')
# print(pQ)

In [20]:
# pQ = np.eye(C.shape[0])
# for i in range(100):
#     Q,R = QR(C)
#     C = R@Q
#     pQ = pQ@Q
    
# print(np.diag(C))
# print(pQ)

In [21]:
# C = np.array([[2,1,1],[1,3,2],[1,0,0]])
C = np.array([[2,1,0],[1,3,1],[0,1,4]])
C11 = C

# Q,R = np.linalg.qr(C)
# print(Q)

# Q,R = QR(C)
# print(Q)

# p_eye = np.eye(C.shape[0])
# for _ in range(100):
#     Q,R = QR(C)
#     p_eye = np.dot(p_eye,Q)
#     C = np.dot(R,Q)

    
# print(np.diag(C))
# print(p_eye)

pQ = np.eye(C.shape[0])
X=C.copy()
X1 = C.copy()
for i in range(100):
        Q,R = QR(X)
        Q = np.array(Q)
        pQ = np.dot(pQ,Q)
        X = np.matmul(R,Q)
        
print(np.diag(X))
print(pQ)

[4.73205081 3.         1.26794919]
[[ 0.21132487 -0.57735027  0.78867513]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.78867513  0.57735027  0.21132487]]


In [22]:
w,v = np.linalg.eig(X1)
print(w)
print(v)

[1.26794919 3.         4.73205081]
[[-0.78867513 -0.57735027  0.21132487]
 [ 0.57735027 -0.57735027  0.57735027]
 [-0.21132487  0.57735027  0.78867513]]


In [23]:
# p_eye = np.eye(C1.shape[0])
# print(p_eye)
# print(w)
# i_eye = np.multiply(w,p_eye)
# i_eye

In [24]:
# M = C1 - i_eye
# M

In [25]:
# pQ = np.eye(C1.shape[0])
# X=X1=C1.copy()
# for i in range(100):
#         Q,R = np.linalg.qr(X)
#         pQ = pQ @ Q;
#         X = R @ Q;

In [26]:
# print(pQ)
# print(np.diag(X))

In [27]:
# w,v = np.linalg.eig(X1)
# print(w)
# print(v)

In [28]:
D = np.array([[5.4,4,7.7],[3.5,-0.7,2.8],[-3.2,5.1,0.8]])
D_q,D_r = QR(D)
D_q
D_r

array([[ 7.18679344e+00,  3.93777840e-01,  6.79301560e+00],
       [ 3.36300722e-17,  6.50729890e+00,  4.64786718e+00],
       [-1.37898911e-14,  9.58493347e-15,  1.49230392e-01]])

In [29]:
pQ = np.eye(D.shape[0])
X=D1=D.copy()
for i in range(100):
        Q,R = np.linalg.qr(X)
        pQ = pQ @ Q
        X = R @ Q
print(X)
print(pQ)

[[ 5.91913923e+00 -8.04869569e+00  3.96727603e+00]
 [ 6.96635182e-65 -1.31545206e+00 -6.62036393e+00]
 [-1.42673563e-82  1.26846839e-17  8.96312838e-01]]
[[ 0.8988889  -0.32577813 -0.29303132]
 [ 0.41069247  0.39327346  0.82259813]
 [-0.15274304 -0.85977009  0.48730377]]


In [30]:
for i in range(100):
        Q,R = QR(X)
        pQ = pQ @ Q.T
        X = R @ Q
print(np.diag(X))
print(pQ)

[ 5.91913923 -1.31545206  0.89631284]
[[ 0.8988889  -0.32577813 -0.29303132]
 [ 0.41069247  0.39327346  0.82259813]
 [-0.15274304 -0.85977009  0.48730377]]


In [31]:
pQ = np.eye(3)
for i in range(100):
        Q,R = QR(X)
        pQ = pQ.dot(Q.T)
        X = R.dot(Q)
print(np.diag(X))
print(pQ)

[ 5.91913923 -1.31545206  0.89631284]
[[ 1.00000000e+00  5.83133238e-14  8.24495364e-14]
 [-6.78345180e-14  1.00000000e+00  7.47580781e-14]
 [-1.17656743e-14 -2.08161929e-14  1.00000000e+00]]


In [32]:
np.linalg.eig(D1)

(array([ 5.91913923, -1.31545206,  0.89631284]),
 array([[ 0.8988889 , -0.45073968, -0.67632405],
        [ 0.41069247, -0.56834012, -0.41283965],
        [-0.15274304,  0.68834821,  0.61004033]]))