In [115]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(precision=7)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA
from sympy import * 

In [116]:
# span = np.array([[1,2,3],[-1,1,1],[1,1,1],[1,1,1]])
span = np.array([[2,1,1],[1,3,2],[1,0,0]])
print(span)
A1 = span

row,col = span.shape
print(row,col)

[[2 1 1]
 [1 3 2]
 [1 0 0]]
3 3


In [117]:
# Setup arrays
# Original Values
vector = []
# Normalized Values
vec_norm = []

In [118]:
# Scale function
def scale(vec_1):
    
    # Test
    v1_scale = np.square(np.linalg.norm(vec_1))
#     print(v1_scale)

    v1 = np.multiply(1/np.sqrt(v1_scale),vec_1)
#     print(v1)
    
    return list(v1)
    
    

In [119]:
def QR(span):
    
    # Setup arrays
    # Original Values
    vector = []
    # Normalized Values
    vec_norm = []
    
    row,col = span.shape
    
    # First Column
    v1 = span[:,0]
    vec_1 = v1
    vector.append(vec_1)

    v1 = scale(vec_1)
    vec_norm.append(v1)
    
    # Subsequent Columns

    start = 1
    end = col

    for j in range(start,end):

        # Column
        projection = span[:,j]
        v = span[:,j]

        #Orthonormal vector
        for i in range(len(vec_norm)):
            #projection
            # dot
            proj_dot = np.dot(v,vec_norm[i])/np.dot(vec_norm[i],vec_norm[i])
            proj = np.multiply(proj_dot,vec_norm[i])
            projection = projection - proj

        v_norm = scale(projection)

        vec_norm.append(v_norm)
        
    # Calculate R
    Q = vec_norm
    Q = np.array(Q)
    R = np.dot(Q,span)
    R = np.array(R)

    
    return Q.T,R


In [120]:
Q,R = QR(span)
print(Q)
print('\n')
print(R)
print('\n')

A = np.dot(R,Q)
print(A)

[[ 0.8164966 -0.2760262  0.5070926]
 [ 0.4082483  0.8970852 -0.1690309]
 [ 0.4082483 -0.3450328 -0.8451543]]


[[ 2.4494897e+00  2.0412415e+00  1.6329932e+00]
 [ 2.7755576e-16  2.4152295e+00  1.5181442e+00]
 [-5.5511151e-16 -5.6621374e-15  1.6903085e-01]]


[[ 3.5        0.591608  -0.4830459]
 [ 1.6057931  1.6428571 -1.6913143]
 [ 0.0690066 -0.0583212 -0.1428571]]


In [121]:
Q,R = np.linalg.qr(span)
print(Q)
print('\n')
print(R)
print('\n')

A = np.dot(R,Q)
print(A)
print('\n')

Q,R = np.linalg.qr(A)
print(Q)
print('\n')
print(R)
print('\n')

A = np.dot(R,Q)
print(A)

[[-0.8164966  0.2760262 -0.5070926]
 [-0.4082483 -0.8970852  0.1690309]
 [-0.4082483  0.3450328  0.8451543]]


[[-2.4494897 -2.0412415 -1.6329932]
 [ 0.        -2.4152295 -1.5181442]
 [ 0.         0.        -0.1690309]]


[[ 3.5        0.591608  -0.4830459]
 [ 1.6057931  1.6428571 -1.6913143]
 [ 0.0690066 -0.0583212 -0.1428571]]


[[-0.9087589  0.4150969 -0.0430331]
 [-0.4169368 -0.9075082  0.0509175]
 [-0.0179172  0.0642138  0.9977753]]


[[-3.8514067 -1.2215516  1.146703 ]
 [ 0.        -1.2490767  1.3251974]
 [ 0.         0.        -0.2078699]]


[[ 3.9887640e+00 -4.1650474e-01  1.2476917e+00]
 [ 4.9704214e-01  1.2186434e+00  1.2586493e+00]
 [ 3.7244529e-03 -1.3348121e-02 -2.0740741e-01]]


In [122]:
Q,R = QR(span)
Q = Q[0:row,0:row]
print(Q)
print('\n')
R = R[0:row,0:row]
print(R)
print('\n')

A = np.dot(R,Q)
print(A)
print('\n')

Q,R = QR(A)
# Q = Q[0:row,0:row]
print(Q.T)
print('\n')
# R = R[0:row,0:row]
# print(R)
# print('\n')

# A = np.dot(R,Q)
# print(A)

[[ 0.8164966 -0.2760262  0.5070926]
 [ 0.4082483  0.8970852 -0.1690309]
 [ 0.4082483 -0.3450328 -0.8451543]]


[[ 2.4494897e+00  2.0412415e+00  1.6329932e+00]
 [ 2.7755576e-16  2.4152295e+00  1.5181442e+00]
 [-5.5511151e-16 -5.6621374e-15  1.6903085e-01]]


[[ 3.5        0.591608  -0.4830459]
 [ 1.6057931  1.6428571 -1.6913143]
 [ 0.0690066 -0.0583212 -0.1428571]]


[[ 0.9087589  0.4169368  0.0179172]
 [-0.4150969  0.9075082 -0.0642138]
 [ 0.0430331 -0.0509175 -0.9977753]]




In [123]:
# span = span.T
eig_val = np.eye(span.shape[0])
X = span.copy()

for i in range(3):
    print(i)
    print('\n')
    Q,R = QR(X)
    print('Q:')
    print(Q.T)
    print('\n')
    print('R:')
    print(R)
    print('\n')
#     Q = Q[0:row,0:row]
#     print('Q:')
#     print(Q.T)
#     print('\n')
#     Q1 = Q[-3:]
#     print('Q1:')
#     print(Q1.T)
#     print('\n')    
    R = R[0:row,0:row]
    print('R0:')
    print(R)
    print('\n')
    X = np.dot(-R,-Q)
    X = X[0:row,0:row]
    print('X:')
    print(X.T)
    print('\n')

0


Q:
[[ 0.8164966  0.4082483  0.4082483]
 [-0.2760262  0.8970852 -0.3450328]
 [ 0.5070926 -0.1690309 -0.8451543]]


R:
[[ 2.4494897e+00  2.0412415e+00  1.6329932e+00]
 [ 2.7755576e-16  2.4152295e+00  1.5181442e+00]
 [-5.5511151e-16 -5.6621374e-15  1.6903085e-01]]


R0:
[[ 2.4494897e+00  2.0412415e+00  1.6329932e+00]
 [ 2.7755576e-16  2.4152295e+00  1.5181442e+00]
 [-5.5511151e-16 -5.6621374e-15  1.6903085e-01]]


X:
[[ 3.5        1.6057931  0.0690066]
 [ 0.591608   1.6428571 -0.0583212]
 [-0.4830459 -1.6913143 -0.1428571]]


1


Q:
[[ 0.9087589  0.4169368  0.0179172]
 [-0.4150969  0.9075082 -0.0642138]
 [ 0.0430331 -0.0509175 -0.9977753]]


R:
[[ 3.8514067e+00  1.2215516e+00 -1.1467030e+00]
 [-6.7868808e-16  1.2490767e+00 -1.3251974e+00]
 [-3.3771994e-15 -7.0407111e-16  2.0786985e-01]]


R0:
[[ 3.8514067e+00  1.2215516e+00 -1.1467030e+00]
 [-6.7868808e-16  1.2490767e+00 -1.3251974e+00]
 [-3.3771994e-15 -7.0407111e-16  2.0786985e-01]]


X:
[[ 3.9887640e+00  4.9704214e-01  3.7244529e-0