In [1]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(precision=3)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA
from sympy import * 

In [2]:
# X =  np.array([1,0,0,1,1,0,1,1,1]).reshape(3,3)
# X =  np.array([1,0,0,0,1,1,0,0,1,1,1,1,1,0,0,1]).reshape(4,4)
row = 6
col = 6
X = np.random.randint(2,size=(row,col))
Y = Z = X.copy()
X
# row,col = X.shape
# # print(X)
# Y = X.copy()
# print(X)

X = np.array([1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,1,1,1,0,1,0,1,1,1,0,1,1,1,0,0,0,1]).reshape(6,6)
Y = X.copy()

if row != col:
    print('Not Equal !')
    X = X.T.dot(X)
    row,col = X.shape
    Y = X.copy()
    print(row,col)

row,col = X.shape
print(X)
print(row,col)

[[1 0 1 0 1 1]
 [1 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 1 1 1 0 1]
 [0 1 1 1 0 1]
 [1 1 0 0 0 1]]
6 6


In [3]:
Q,R = np.linalg.qr(Y)
Q1 = Q.copy()

print(Q)
print('\n')
print(R)

print('\n')

X =Q.dot(R)
print(X)

print('\n')

# np.dot(Q[row-1],Q[row-1].T)

[[-5.000e-01 -1.508e-01  4.308e-01  2.041e-01  6.944e-01 -1.332e-01]
 [-5.000e-01 -1.508e-01  4.308e-01  2.041e-01 -6.944e-01  1.332e-01]
 [-5.000e-01 -1.508e-01 -2.462e-01 -8.165e-01 -6.836e-17 -4.148e-17]
 [-0.000e+00  6.030e-01  3.077e-01 -2.041e-01  1.332e-01  6.944e-01]
 [-0.000e+00  6.030e-01  3.077e-01 -2.041e-01 -1.332e-01 -6.944e-01]
 [-5.000e-01  4.523e-01 -6.155e-01  4.082e-01 -6.836e-17  6.260e-17]]


[[-2.000e+00 -5.000e-01 -1.000e+00  0.000e+00 -1.500e+00 -1.000e+00]
 [ 0.000e+00  1.658e+00  9.045e-01  1.206e+00 -4.523e-01  1.508e+00]
 [ 0.000e+00  0.000e+00  1.477e+00  6.155e-01  6.155e-01  4.308e-01]
 [ 0.000e+00  0.000e+00  0.000e+00 -4.082e-01 -4.082e-01  2.041e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00 -5.452e-17  6.944e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00 -1.332e-01]]


[[ 1.000e+00  5.551e-17  1.000e+00  5.551e-17  1.000e+00  1.000e+00]
 [ 1.000e+00 -1.665e-16  1.000e+00 -5.551e-17  1.000e+00 -5.551e-17]
 [ 1.000e+00  0.000e+00 -8.3

In [4]:
# Initialize arrays

U = []
V_norm = []
U_Norm = []
A = []
projection = []

In [5]:
# First Column

a1 = X[:,0]
A.append(a1)
u1 = a1
print(u1)
U.append(u1)

# Normalization
a1_norm = np.linalg.norm(a1)
u1_normalized = a1/a1_norm
print(u1_normalized)
V_norm.append(u1_normalized)
print(V_norm)

V_norm_1 = np.array(V_norm).T
vv = np.multiply(V_norm_1[0],Y)
print(vv)

# V_norm = np.array(V_norm)
# R1 = np.dot(V_norm,Y)
# print(R1)
# R = np.dot(V_norm[0],Y)[0]
# print(R)

# V_norm = np.array(V_norm)
# R = np.dot(V_norm,Y)[0]
# print(R)

# V_norm = np.array(V_norm)
# R1 = np.dot(V_norm,Y)
# print(R1)
# R = np.dot(V_norm[0],Y)[0]
# print(R)

[1. 1. 1. 0. 0. 1.]
[0.5 0.5 0.5 0.  0.  0.5]
[array([0.5, 0.5, 0.5, 0. , 0. , 0.5])]
[[0.5 0.  0.5 0.  0.5 0.5]
 [0.5 0.  0.5 0.  0.5 0. ]
 [0.5 0.  0.  0.  0.5 0. ]
 [0.  0.5 0.5 0.5 0.  0.5]
 [0.  0.5 0.5 0.5 0.  0.5]
 [0.5 0.5 0.  0.  0.  0.5]]


In [6]:
# Subsequent Columns
for j in range(1,row):
    a = X[:,j]
    u = a
    A.append(a)
    
    # Projection
    projection = []
    for i in range(j):

        # Dot products
        # Denominator
        denom = U[i-1].dot(U[i-1].T)
        # Numerator
        num = U[i-1].dot(a)
        # Multiple
        vec = np.multiply(num/denom,U[i-1])
        projection.append(vec)
        
#     print(projection)
    
    for k in range(len(projection)):
        u1 = a - projection[k]
        a = u1
#     print(a)
    
    U.append(u1)
    
    # Normalization
    v_norm = np.linalg.norm(u1)
    v_normalized = u1/v_norm
#     print(v_normalized)
    V_norm.append(v_normalized)
    
# V_norm = np.array(V_norm)
# R = np.dot(V_norm[1],Y)
# print(R)

V_norm = np.array(V_norm)
print('V norm:', V_norm)
R1 = np.dot(V_norm,Y)
print(R1)
R_0 = []
for i in range(1,row):
    print('i:',i)
    R = np.dot(V_norm[row-i],Y)[0]
    R_0.append(R)
print(R_0)

print('\n')
# U_norm = []
# for i in V_norm:
#     U_norm.append(list(i))
print(U)
print('\n')
print(V_norm)
# print(V_norm[0])
# print('\n')
# print(U)

V norm: [[ 0.5    0.5    0.5    0.     0.     0.5  ]
 [-0.151 -0.151 -0.151  0.603  0.603  0.452]
 [ 0.431  0.431 -0.246  0.308  0.308 -0.615]
 [-0.204 -0.204  0.816  0.204  0.204 -0.408]
 [ 0.22  -0.439 -0.549 -0.11  -0.11  -0.659]
 [ 0.551 -0.675 -0.309 -0.062 -0.062 -0.371]]
[[ 2.000e+00  5.000e-01  1.000e+00  0.000e+00  1.500e+00  1.000e+00]
 [ 1.110e-16  1.658e+00  9.045e-01  1.206e+00 -4.523e-01  1.508e+00]
 [-1.110e-16  0.000e+00  1.477e+00  6.155e-01  6.155e-01  4.308e-01]
 [ 1.110e-16  3.886e-16  3.331e-16  4.082e-01  4.082e-01 -2.041e-01]
 [-1.427e+00 -8.781e-01 -4.391e-01 -2.195e-01 -7.683e-01 -6.586e-01]
 [-8.036e-01 -4.945e-01 -2.473e-01 -1.236e-01 -4.327e-01  5.667e-02]]
i: 1
i: 2
i: 3
i: 4
i: 5
[-0.8036327476661118, -1.4269353798659745, 5.551115123125783e-17, -1.1102230246251565e-16, 1.1102230246251565e-16]


[array([1., 1., 1., 0., 0., 1.]), array([-0.25, -0.25, -0.25,  1.  ,  1.  ,  0.75]), array([ 0.636,  0.636, -0.364,  0.455,  0.455, -0.909]), array([-0.083, -0.083,

In [7]:
V_norm = np.array(V_norm)
print('V norm:', V_norm)
# R1 = np.dot(V_norm.T,Y)
# print(R1)
R_0 = []
for i in range(1,row):
    print('i:',i)
    R = np.dot(V_norm[row-i],Y)[0]
    R_0.append(R)
print(R_0)

for i in range(len(R_0)):
    if abs(R_0[i]) > 1e-2:
        a1 = X[:,0]
        A[0] = a1
        u1 = a1
        print(u1)
#         U.append(u1)
        U[0] = u1

        # Normalization
        a1_norm = np.linalg.norm(a1)
        u1_normalized = a1/a1_norm
        print(u1_normalized)
#         V_norm.append(u1_normalized)
        V_norm[0] = u1_normalized
        print(V_norm)

V norm: [[ 0.5    0.5    0.5    0.     0.     0.5  ]
 [-0.151 -0.151 -0.151  0.603  0.603  0.452]
 [ 0.431  0.431 -0.246  0.308  0.308 -0.615]
 [-0.204 -0.204  0.816  0.204  0.204 -0.408]
 [ 0.22  -0.439 -0.549 -0.11  -0.11  -0.659]
 [ 0.551 -0.675 -0.309 -0.062 -0.062 -0.371]]
i: 1
i: 2
i: 3
i: 4
i: 5
[-0.8036327476661118, -1.4269353798659745, 5.551115123125783e-17, -1.1102230246251565e-16, 1.1102230246251565e-16]
[1. 1. 1. 0. 0. 1.]
[0.5 0.5 0.5 0.  0.  0.5]
[[ 0.5    0.5    0.5    0.     0.     0.5  ]
 [-0.151 -0.151 -0.151  0.603  0.603  0.452]
 [ 0.431  0.431 -0.246  0.308  0.308 -0.615]
 [-0.204 -0.204  0.816  0.204  0.204 -0.408]
 [ 0.22  -0.439 -0.549 -0.11  -0.11  -0.659]
 [ 0.551 -0.675 -0.309 -0.062 -0.062 -0.371]]
[1. 1. 1. 0. 0. 1.]
[0.5 0.5 0.5 0.  0.  0.5]
[[ 0.5    0.5    0.5    0.     0.     0.5  ]
 [-0.151 -0.151 -0.151  0.603  0.603  0.452]
 [ 0.431  0.431 -0.246  0.308  0.308 -0.615]
 [-0.204 -0.204  0.816  0.204  0.204 -0.408]
 [ 0.22  -0.439 -0.549 -0.11  -0.11  -

In [8]:
# # Subsequent Columns
# for j in range(1,row):
#     a = X[:,j]
#     u = a
#     A.append(a)
    
#     # Projection
#     projection = []
#     for i in range(j):

#         # Dot products
#         # Denominator
#         denom = U[i-1].dot(U[i-1].T)
#         # Numerator
#         num = U[i-1].dot(a)
#         # Multiple
#         vec = np.multiply(num/denom,U[i-1])
#         projection.append(vec)
        
# #     print(projection)
    
#     for k in range(len(projection)):
#         u1 = a - projection[k]
#         a = u1
# #     print(a)
    
#     U.append(u1)
    
#     # Normalization
#     v_norm = np.linalg.norm(u1)
#     v_normalized = u1/v_norm
# #     print(v_normalized)
#     V_norm.append(v_normalized)
    
# # V_norm = np.array(V_norm)
# # R = np.dot(V_norm[1],Y)
# # print(R)

# V_norm = np.array(V_norm)
# print('V norm:', V_norm)
# R1 = np.dot(V_norm,Y)
# print(R1)
# R_0 = []
# for i in range(1,row):
#     print('i:',i)
#     R = np.dot(V_norm[row-i],Y)[0]
#     R_0.append(R)
# print(R_0)

# print('\n')
# # U_norm = []
# # for i in V_norm:
# #     U_norm.append(list(i))
# print(U)
# print('\n')
# print(V_norm)
# # print(V_norm[0])
# # print('\n')
# # print(U)

In [9]:
# V_norm = np.array(V_norm)
# R = np.dot(V_norm[1],Y)[0]
# #     print(R)

In [10]:
err = []
for i in range(len(U)):
    err.append(np.dot(U[i],U[i].T))
    
print(err)

# print(V_norm[3].T.dot(V_norm[3]))

[4.0, 2.7500000000000004, 2.181818181818182, 0.16666666666666655, 6.394087415365623e-32, 1.3674698795180726]


In [11]:
# for i in range(row):
#     Q1[i,:] = np.multiply(-1,Q1[i,:])
# print(Q1)
# print('\n')
# print(err)
# print('\n')
# print(V_norm)

In [12]:
V_norm = np.array(V_norm)
R = np.dot(V_norm[1],Y)
print(R)

# V_norm_0 = V_norm[0].T.dot(Y)
# print(V_norm_0)

V_norm_1 = V_norm.T
print("V_norm_1:", V_norm_1)
R = np.dot(V_norm_1,Y)
R1 = np.dot(V_norm_1[0],Y)
print(R)
print(R1)

[ 1.110e-16  1.658e+00  9.045e-01  1.206e+00 -4.523e-01  1.508e+00]
V_norm_1: [[ 0.5   -0.151  0.431 -0.204  0.22   0.551]
 [ 0.5   -0.151  0.431 -0.204 -0.439 -0.675]
 [ 0.5   -0.151 -0.246  0.816 -0.549 -0.309]
 [ 0.     0.603  0.308  0.204 -0.11  -0.062]
 [ 0.     0.603  0.308  0.204 -0.11  -0.062]
 [ 0.5    0.452 -0.615 -0.408 -0.659 -0.371]]
[[ 1.331  0.567  0.365  0.015  0.78   1.067]
 [ 0.105 -1.318 -0.294 -0.643  0.78  -0.818]
 [-0.206 -0.041  0.617  0.268  0.103  0.459]
 [ 0.849  0.033  0.697  0.094  0.911  0.033]
 [ 0.849  0.033  0.697  0.094  0.911  0.033]
 [-0.034 -1.438 -0.115 -1.067  0.337 -0.938]]
[1.331 0.567 0.365 0.015 0.78  1.067]


In [13]:
def QR2(Y):
    for _ in range(10):
    # Initialize arrays

        U = []
        V_norm = []
        U_Norm = []
        A = []
        projection = []
        Z = Y.copy()

        # First Column

        a1 = Y[:,0]
        A.append(a1)
        u1 = a1
        print(u1)
        U.append(u1)

        # Normalization
        a1_norm = np.linalg.norm(a1)
        u1_normalized = a1/a1_norm
        print(u1_normalized)
        V_norm.append(u1_normalized)
        
            
        print('u1_normalized',u1_normalized)
        
        for m in range(1,len(u1_normalized)):
#             print("m:", u1_normalized[m])
            if abs(u1_normalized[m]) < 0 or u1_normalized[m] == nan:
               # Normalization
            
                a1 = Y[:,0:1]
                A[0] = a1
                u1 = a1
                print(u1)
#                 U.append(u1)
                U[0] = u1
            
                a1_norm = np.linalg.norm(a1)
                u1_normalized = a1/(a1_norm + 1e-15)
                print(u1_normalized)
#                 V_norm.append(u1_normalized)
                print('mistake!')
                V_norm[0] = u1_normalized
        
#         print('u1_normalized',u1_normalized)

        # Subsequent Columns
        for j in range(1,row):
            a = Y[:,j]
            u = a
            A.append(a)

            # Projection
            projection = []
            for i in range(j):

                # Dot products
                # Denominator
                denom = (U[i-1].dot(U[i-1].T) + 1e-15)
                # Numerator
                num = U[i-1].dot(a)
                # Multiple
                vec = np.multiply(num/denom,U[i-1])
                projection.append(vec)

        #     print(projection)

            for k in range(len(projection)):
                u1 = a - projection[k]
                a = u1
            print("a_0:",a)

            U.append(u1)

            # Normalization
            v_norm = np.linalg.norm(u1)
            v_normalized = u1/(v_norm + 1e-15)
        #     print(v_normalized)
            V_norm.append(v_normalized)

        print('\n')
        # U_norm = []
        # for i in V_norm:
        #     U_norm.append(list(i))
        print(U)
        print('\n')
        print(V_norm)
        # print(V_norm[0])
        # print('\n')
        # print(U)

        V_norm = np.array(V_norm)
        R = np.dot(V_norm,Z)
        V_norm_1 = V_norm
        print('V_norm_1:',V_norm_1)
        R1 = np.dot(V_norm_1[0],Z)
    
    return V_norm_1,V_norm.T,R,R1

In [14]:

V,Q,R,R1 = QR2(Z)
# print(Q)
# print('\n')
# print(R)
# print('\n')
# print(R1)

[0 0 0 1 1 0]
[0.    0.    0.    0.707 0.707 0.   ]
u1_normalized [0.    0.    0.    0.707 0.707 0.   ]
a_0: [1. 0. 1. 0. 0. 0.]
a_0: [0.000e+00 0.000e+00 0.000e+00 4.441e-16 4.441e-16 0.000e+00]
a_0: [0. 0. 0. 0. 0. 1.]
a_0: [0. 1. 0. 0. 0. 0.]
a_0: [ 4.441e-16  1.110e-15  4.441e-16 -5.000e-01  5.000e-01  1.110e-15]


[array([0, 0, 0, 1, 1, 0]), array([1., 0., 1., 0., 0., 0.]), array([0.000e+00, 0.000e+00, 0.000e+00, 4.441e-16, 4.441e-16, 0.000e+00]), array([0., 0., 0., 0., 0., 1.]), array([0., 1., 0., 0., 0., 0.]), array([ 4.441e-16,  1.110e-15,  4.441e-16, -5.000e-01,  5.000e-01,  1.110e-15])]


[array([0.   , 0.   , 0.   , 0.707, 0.707, 0.   ]), array([0.707, 0.   , 0.707, 0.   , 0.   , 0.   ]), array([0.   , 0.   , 0.   , 0.273, 0.273, 0.   ]), array([0., 0., 0., 0., 0., 1.]), array([0., 1., 0., 0., 0., 0.]), array([ 6.280e-16,  1.570e-15,  6.280e-16, -7.071e-01,  7.071e-01,  1.570e-15])]
V_norm_1: [[ 0.000e+00  0.000e+00  0.000e+00  7.071e-01  7.071e-01  0.000e+00]
 [ 7.071e-01  

In [15]:
print(V)
print('\n')
print(Q)
print('\n')
print(R)
print('\n')
print(R1)

[[ 0.000e+00  0.000e+00  0.000e+00  7.071e-01  7.071e-01  0.000e+00]
 [ 7.071e-01  0.000e+00  7.071e-01  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  2.728e-01  2.728e-01  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  1.000e+00]
 [ 0.000e+00  1.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 6.280e-16  1.570e-15  6.280e-16 -7.071e-01  7.071e-01  1.570e-15]]


[[ 0.000e+00  7.071e-01  0.000e+00  0.000e+00  0.000e+00  6.280e-16]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  1.000e+00  1.570e-15]
 [ 0.000e+00  7.071e-01  0.000e+00  0.000e+00  0.000e+00  6.280e-16]
 [ 7.071e-01  0.000e+00  2.728e-01  0.000e+00  0.000e+00 -7.071e-01]
 [ 7.071e-01  0.000e+00  2.728e-01  0.000e+00  0.000e+00  7.071e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00  0.000e+00  1.570e-15]]


[[1.414e+00 0.000e+00 1.414e+00 1.414e+00 0.000e+00 7.071e-01]
 [0.000e+00 1.414e+00 0.000e+00 0.000e+00 0.000e+00 1.414e+00]
 [5.456e-01 0.000e+00 5.456e-01 5.456e-0