In [7]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(precision=7)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA
from sympy import * 

In [8]:
# Scale function
def scale(vec_1):
    
    # Test
    v1_scale = np.square(np.linalg.norm(vec_1))
#     print(v1_scale)

    v1 = np.multiply(1/np.sqrt(v1_scale + 1e-15),vec_1)
#     print(v1)
    
    return list(v1)
    
    
def QR(span):
    
    # Setup arrays
    # Original Values
    vector = []
    # Normalized Values
    vec_norm = []

    # Size of array
    row,col = span.shape
    
    # First Column
    v1 = span[:,0]
    vec_1 = v1
    vector.append(vec_1)

    v1 = scale(vec_1)
    vec_norm.append(v1)
    
    # Subsequent Columns

    start = 1
    end = col

    for j in range(start,end):

        # Column
        projection = span[:,j]
        v = span[:,j]

        #Orthonormal vector
        for i in range(len(vec_norm)):
            #projection
            # dot
            proj_dot = np.dot(v,vec_norm[i])/(np.dot(vec_norm[i],vec_norm[i]) + 1e-15)
            proj = np.multiply(proj_dot,vec_norm[i])
            projection = projection - proj

        v_norm = scale(projection)

        vec_norm.append(v_norm)
        
    # Calculate R
    Q = vec_norm
    Q = np.array(Q)
    R = np.dot(Q,span)
    R = np.array(R)

    
    return Q.T,R

def eigenspace(span):
    
    eig_vec = np.eye(span.shape[0])
    X = span.copy()

    for _ in range(100):
        Q,R = QR(X)
        eig_vec = np.dot(eig_vec,Q)
        X = np.dot(R,Q)
        eig_val = np.diag(X)
        
    return eig_val,eig_vec, X


In [9]:
# Matrix
A = np.array([[1,2],[2,4]])

# Vector 1
vec_1 = np.array([[1,1]])

# Vector 2
vec_2 = np.array([[1,2]])

A.T.dot(A)

array([[ 5, 10],
       [10, 20]])

In [10]:
# Product

Ax_1 = A.dot(vec_1.T)
print(Ax_1)

Ax_2 = A.dot(vec_2.T)
print(Ax_2)

[[3]
 [6]]
[[ 5]
 [10]]


In [11]:
A = np.array([[0.8,0.3],[0.2,0.7]])
print(A)
w,v,u = eigenspace(A)
print(w)
print(v)
print(u)

# Ax_1 = A.dot()

[[0.8 0.3]
 [0.2 0.7]]
[1.  0.5]
[[ 0.8320503 -0.5547002]
 [ 0.5547002  0.8320503]]
[[1.000000e+00 1.000000e-01]
 [3.807978e-16 5.000000e-01]]


In [12]:
v.T.dot(v)

array([[1.0000000e+00, 1.8084277e-14],
       [1.8084277e-14, 1.0000000e+00]])