In [1]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
import matplotlib.pyplot as plt
import math 
import pandas as pd

In [2]:
# span = np.array([[1,2,3],[-1,1,1],[1,1,1],[1,1,1]])
# print(span)
# A1 = span

In [3]:
row = 5
col = 5
span = np.random.randint(10,size=(row,col))
print(span)
A1 = span

[[9 0 5 5 7]
 [6 6 1 7 3]
 [2 9 9 2 4]
 [0 3 4 2 0]
 [2 6 0 5 4]]


In [4]:
row,col = span.shape
row

5

In [5]:
v1 = span[:,0]
v2 = span[:,1]
v3 = span[:,2]
v4 = span[:,3]
v5 = span[:,4]

In [6]:
# Setup arrays
# Original Values
vector = []
# Normalized Values
vec_norm = []

In [7]:
# First Column

v1 = span[:,0]
vec_1 = v1
print(vec_1)
vector.append(vec_1)

# Test
v1_scale = np.square(np.linalg.norm(vec_1))
print(v1_scale)

v1 = np.multiply(1/np.sqrt(v1_scale),vec_1)
print(v1)
vec_norm.append(v1)


[9 6 2 0 2]
125.00000000000001
[0.80498447 0.53665631 0.17888544 0.         0.17888544]


In [8]:
def QR(span): 
    
    # Copy matrix
    A1 = span
    
    # Size of array
    row,col = span.shape
    
    # Setup arrays
    # Original Values
    vector = []
    # Normalized Values
    vec_norm = []
    
    # First Column
    v1 = span[:,0]
    vec_1 = v1
#     print(vec_1)
    vector.append(vec_1)

    # Test
    v1_scale = np.square(np.linalg.norm(vec_1))
#     print(v1_scale)

    v1 = np.multiply(1/np.sqrt(v1_scale),vec_1)
#     print(v1)
    vec_norm.append(v1)     

    # Subsequent Columns

    start = 1
    end = col

    for i in range(start,end):
        
        # Initialize vectors
        length = []
        projection = []
        project = []

        # Columns
        v = span[:,i]

        for i in vector:
            leng = np.dot(i,v)
            length.append(leng)
            proj_0 = np.dot(i,i)
            projection.append(proj_0)
            proj_1 = leng/proj_0
            project.append(proj_1)

#         print(length)
#         print(projection)
#         print(project)
        
        # Factorization
        a = min(projection)
#         print('a:',a)

        # QR equation
        vec_0 = 0
        vec_1 = np.multiply(a,v)
        for i in range(len(vector)):
            vec_0 = vec_0 - np.multiply(project[i]*a,vector[i])

        vect_0 = vec_1 + vec_0    
#         print(vect_0)
        vector.append(vect_0)

        # Scaling vector    
        # Scale
        v_scale = np.square(np.linalg.norm(vect_0))
#         print(v_scale)

        v_norm = np.multiply(1/np.sqrt(v_scale + 1e-20),vect_0)
#         print(v_norm)

        v = v_norm
        vec_norm.append(v_norm)
#         print('v norm:', v_norm)
#         print('\n')
#         print(vector)
#         print('\n')
#         print(vec_norm)
#         print('\n')
#         print(np.array(vec_norm).T)
        
    # Calculate R
    # Q matrix
    Q = np.array(vec_norm)
    # A1 = np.multiply(1,A1)
    R = np.dot(Q,A1)
#     print(R)
    
    return Q.T, R

In [9]:
# Function
Q,R = QR(A1)

In [10]:
print(Q)
print("\n")
print(R)

[[ 0.80498447 -0.4214197   0.3221911   0.06726719  0.25704757]
 [ 0.53665631  0.25114911 -0.50368337 -0.03837761 -0.62749848]
 [ 0.17888544  0.70449455  0.54193683 -0.42110707  0.02570476]
 [ 0.          0.26604779  0.34304963  0.87300133 -0.22227055]
 [ 0.17888544  0.43844676 -0.48074669  0.23353755  0.70007662]]


[[ 1.11803399e+01  5.90321946e+00  6.17154762e+00  9.03371463e+00  8.67594375e+00]
 [-1.11022302e-16  1.12761696e+01  5.54869272e+00  3.78426378e+00  2.37527468e+00]
 [ 1.11022302e-16  1.22124533e-15  7.35690214e+00 -2.54858859e+00  9.89048183e-01]
 [ 8.32667268e-16 -3.05311332e-15 -8.88178420e-16  2.13916896e+00 -3.94540594e-01]
 [-2.22044605e-16 -2.66453526e-15 -2.22044605e-15 -4.44089210e-16  2.81996305e+00]]


In [11]:
# # Calculate R
# Q = vec_norm
# # A1 = np.multiply(1,A1)
# R = np.dot(Q,A1)
# print(R)

In [12]:
# Function
C = np.array([[2,1,0],[1,3,1],[0,1,4]])
Q,R = QR(C)
print(Q)
print(R)

A2 = np.dot(Q,R)
print(A2)

[[ 0.89442719 -0.40824829  0.18257419]
 [ 0.4472136   0.81649658 -0.36514837]
 [ 0.          0.40824829  0.91287093]]
[[2.23606798e+00 2.23606798e+00 4.47213595e-01]
 [0.00000000e+00 2.44948974e+00 2.44948974e+00]
 [0.00000000e+00 1.11022302e-16 3.28633535e+00]]
[[2.00000000e+00 1.00000000e+00 1.28782024e-16]
 [1.00000000e+00 3.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00 4.00000000e+00]]


In [13]:
A = np.array([[2,1,0],[1,3,1],[0,1,4]])
pQ = np.eye(3)
X=A.copy()
Y=A.copy()
for i in range(100):
        Q,R = QR(X)
        pQ = pQ.dot(Q)
        X = R.dot(Q)
        
print(pQ)
print(X)

[[ 0.21132487 -0.57735027  0.78867513]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.78867513  0.57735027  0.21132487]]
[[ 4.73205081e+00 -2.16734458e-16 -2.65771039e-16]
 [ 7.62491445e-20  3.00000000e+00 -1.43222913e-16]
 [-1.46181478e-31  4.85380545e-32  1.26794919e+00]]


In [14]:
np.linalg.eig(Y)

(array([1.26794919, 3.        , 4.73205081]),
 array([[-0.78867513, -0.57735027,  0.21132487],
        [ 0.57735027, -0.57735027,  0.57735027],
        [-0.21132487,  0.57735027,  0.78867513]]))