In [255]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(precision=7)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA
from sympy import * 

In [256]:
# Scale function
def scale(vec_1):
    
    # Test
    v1_scale = np.square(np.linalg.norm(vec_1))
#     print(v1_scale)

    v1 = np.multiply(1/np.sqrt(v1_scale + 1e-15),vec_1)
#     print(v1)
    
    return list(v1)
    
    
def QR(span):
    
    # Setup arrays
    # Original Values
    vector = []
    # Normalized Values
    vec_norm = []

    # Size of array
    row,col = span.shape
    
    # First Column
    v1 = span[:,0]
    vec_1 = v1
    vector.append(vec_1)

    v1 = scale(vec_1)
    vec_norm.append(v1)
    
    # Subsequent Columns

    start = 1
    end = col

    for j in range(start,end):

        # Column
        projection = span[:,j]
        v = span[:,j]

        #Orthonormal vector
        for i in range(len(vec_norm)):
            #projection
            # dot
            proj_dot = np.dot(v,vec_norm[i])/(np.dot(vec_norm[i],vec_norm[i]) + 1e-15)
            proj = np.multiply(proj_dot,vec_norm[i])
            projection = projection - proj

        v_norm = scale(projection)

        vec_norm.append(v_norm)
        
    # Calculate R
    Q = vec_norm
    Q = np.array(Q)
    R = np.dot(Q,span)
    R = np.array(R)

    
    return Q.T,R

def eigenspace(span):
    
    eig_vec = np.eye(span.shape[0])
    X = span.copy()

    for _ in range(100):
        Q,R = QR(X)
        eig_vec = np.dot(eig_vec,Q)
        X = np.dot(R,Q)
        eig_val = np.diag(X)
        
    return eig_val,eig_vec, X


In [257]:
def SVD(A):
    
    # Size of array
    row,col = A.shape
    print('row:', row)
    print('col:', col)
    
    
    # Arrays
    if row < col:
        A1 = A.dot(A.T)
#         print(A1)
    else:
        A1 = A.T.dot(A)
#         print(A1)
        
    # Size of arrays
    row_A,col_A = A1.shape
    print('row_A:', row_A)
    print('col_A:', col_A)
    
    # Eigenspace
    eig_val_A1,eig_vec_A1,x_A1 = eigenspace(A1)
    
    # Eigenvector
    V = eig_vec_A1
#     print('V:',V)
    
    # Singular values
    sigma_A1 = []
    eig_val = eig_val_A1
    for i in range(len(eig_val)):
        sigma_A1.append(np.sqrt(eig_val[i]))
        
    # Sigma
    Sigma = np.sqrt(eig_val_A1) * np.eye(row_A)

    # CV
    if row > col:
        CV = A.dot(V.T)
        CV_0 = CV.copy()
    elif row < col:
        CV = A.T.dot(V.T)
        CV_0 = CV.copy()
        
    
    # Normalize vectors
    # CV = CV.T
#     print(CV)

#     row,col = CV.shape

    for i in range(row):
        CV[i] = CV[i]/(np.linalg.norm(CV[i]) + 1e-15)


    # Solve for U
    U = CV_0.dot(np.linalg.inv(Sigma))
    
    # V
#     if row_A != row and col_A != col:
#         V = V.T

#     if col > row or col < row:
#         V = V.T

#     if col > row:
#         V = V.T
#     elif col < row:
#         V = V.T


        
    return U, Sigma, V
    



In [258]:
# A = np.array([[1,1,1],[0,1,-1],[-1,1,2],[2,-1,0]])
# A = np.array([[5,5],[-1,7]])
# A = np.array([[1,-8,3,9],[-6,7,-3,5]])
# A = np.array([[4,3,0],[-8,2,-3],[4,5,5],[7,-10,-6]])
# A = np.array([[2,4],[1,3],[0,0],[0,0]])

row = 4
col = 5
A = np.random.randint(-10,10,size=(row,col))

B = A.copy()

print(A)

row,col = A.shape
print(row)
print(col)

[[  5   7  -8   4   2]
 [ -6   5 -10   9   9]
 [  1  -9   5   2  -4]
 [ -3  -4   3  -4   9]]
4
5


In [259]:
U,E,V = np.linalg.svd(B)
print(U)
print(E)
print(V)

[[-0.4836638  0.4388698 -0.1776898  0.7361311]
 [-0.7726998 -0.3710025  0.4865276 -0.1690652]
 [ 0.4055006 -0.047237   0.7754008  0.4817588]
 [ 0.0676282 -0.8170184 -0.3612075  0.4443382]]
[21.709841  13.1167791  8.5397481  4.7650408]
[[ 0.111493  -0.5144747  0.6368861 -0.3845475 -0.4115633]
 [ 0.5202636  0.3743513 -0.189694   0.1212231 -0.7338311]
 [-0.228179  -0.5087934 -0.0761587  0.7803065 -0.2727366]
 [ 0.8066648 -0.3789244 -0.0958205  0.1278274  0.4244841]
 [ 0.1188334  0.4390017  0.7371639  0.4606627  0.1937407]]


In [260]:
U,Sigma,V = SVD(B)
print(U)
print(Sigma)
print(V)
# print('\n')
# print(U.T.dot(U))

row: 4
col: 5
row_A: 4
col_A: 4
[[ 0.1227763  0.2005986 -0.3490502 -1.4552811]
 [-0.0070944  0.2715166 -1.3475763  1.0671912]
 [ 0.0847234 -0.6073275  0.9477933 -1.7003383]
 [-0.2448234  0.6159391 -0.1842096  0.9617725]
 [ 0.2005283  0.1080086  0.0993422  2.6572245]]
[[21.709841   0.         0.         0.       ]
 [ 0.        13.1167791  0.         0.       ]
 [ 0.         0.         8.5397481  0.       ]
 [ 0.         0.         0.         4.7650408]]
[[ 0.4836638 -0.4388698 -0.1776898  0.7361311]
 [ 0.7726998  0.3710025  0.4865276 -0.1690652]
 [-0.4055006  0.047237   0.7754008  0.4817588]
 [-0.0676282  0.8170184 -0.3612075  0.4443382]]


In [261]:
print(B)
row,col = B.shape
print(row)
print(col)

# A_0 = np.dot(Sigma.T,V.T)
# A = U.dot(A_0).T
# A = A_0.dot(U)
# print(A)

if col < row:
    
    print('A')

    A_0 = np.dot(Sigma.T,V.T)
    # print(A_0)
    print(U)

#     A = U.dot(A_0).T
    A = U.dot(Sigma).dot(V).T
    print(A)
    
elif col > row:
    
    print('B')
    
    A_0 = np.dot(Sigma.T,V.T)
    # print(A_0)
    print(U)

#     A = U.dot(A_0)
    A = U.dot(Sigma).dot(V)
    print(A)

[[  5   7  -8   4   2]
 [ -6   5 -10   9   9]
 [  1  -9   5   2  -4]
 [ -3  -4   3  -4   9]]
4
5
B
[[ 0.1227763  0.2005986 -0.3490502 -1.4552811]
 [-0.0070944  0.2715166 -1.3475763  1.0671912]
 [ 0.0847234 -0.6073275  0.9477933 -1.7003383]
 [-0.2448234  0.6159391 -0.1842096  0.9617725]
 [ 0.2005283  0.1080086  0.0993422  2.6572245]]
[[  5.  -6.   1.  -3.]
 [  7.   5.  -9.  -4.]
 [ -8. -10.   5.   3.]
 [  4.   9.   2.  -4.]
 [  2.   9.  -4.   9.]]
