In [1]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
# np.set_printoptions(precision=7)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA
from sympy import * 

In [2]:
# Scale function
def scale(vec_1):
    
    # Test
    v1_scale = np.square(np.linalg.norm(vec_1))
#     print(v1_scale)

    v1 = np.multiply(1/np.sqrt(v1_scale + 1e-15),vec_1)
#     print(v1)
    
    return list(v1)
    
    
def QR(span):
    
    # Setup arrays
    # Original Values
    vector = []
    # Normalized Values
    vec_norm = []

    # Size of array
    row,col = span.shape
    
    # First Column
    v1 = span[:,0]
    vec_1 = v1
    vector.append(vec_1)

    v1 = scale(vec_1)
    vec_norm.append(v1)
    
    # Subsequent Columns

    start = 1
    end = col

    for j in range(start,end):

        # Column
        projection = span[:,j]
        v = span[:,j]

        #Orthonormal vector
        for i in range(len(vec_norm)):
            #projection
            # dot
            proj_dot = np.dot(v,vec_norm[i])/(np.dot(vec_norm[i],vec_norm[i]) + 1e-15)
            proj = np.multiply(proj_dot,vec_norm[i])
            projection = projection - proj

        v_norm = scale(projection)

        vec_norm.append(v_norm)
        
    # Calculate R
    Q = vec_norm
    Q = np.array(Q)
    R = np.dot(Q,span)
    R = np.array(R)

    
    return Q.T,R

def eigenspace(span):
    
    eig_vec = np.eye(span.shape[0])
    X = span.copy()

    for _ in range(100):
        Q,R = QR(X)
        eig_vec = np.dot(eig_vec,Q)
        X = np.dot(R,Q)
        eig_val = np.diag(X)
        
    return eig_val,eig_vec, X


In [3]:
# A = np.array([[4,4],[-3,3]])
# A = np.array([[2,4],[1,3],[0,0],[0,0]])

row = 6
col = 5
A = np.random.randint(-10,10,size=(row,col))

row,col = A.shape

if col > row:
    np.set_printoptions(precision=0)
    

B = A.copy()

print(A)

[[ -5   7  -8   6 -10]
 [ -4  -9  -8   0   7]
 [ -5  -2  -4   3  -1]
 [ -7  -4  -8   4  -6]
 [ -9 -10   3   2   9]
 [ -5   8  -6  -9   0]]


In [4]:
A1 = A.dot(A.T)
print(A1)
A2 = np.dot(A.T,A)
print(A2)

[[ 274  -49   71  155 -127   75]
 [ -49  210   63   86  165   -4]
 [  71   63   55   93   50    6]
 [ 155   86   93  181   33   15]
 [-127  165   50   33  275  -71]
 [  75   -4    6   15  -71  206]]
[[ 221   89  151  -46  -12]
 [  89  314  -22  -72 -197]
 [ 151  -22  253  -32  103]
 [ -46  -72  -32  146  -69]
 [ -12 -197  103  -69  267]]


In [5]:
# Eigenvalues
eig_val_A1,eig_vec_A1,x_A1 = eigenspace(A1)
print(eig_val_A1)
print(eig_vec_A1)
print(x_A1)

print('\n')

eig_val_A2,eig_vec_A2,x_A2 = eigenspace(A2)
print(eig_val_A2)
print(eig_vec_A2)
print(x_A2)

print('\n')

V = eig_vec_A2.T
print('V:',V)

[519.44107203 430.53689345 181.89946385  58.01787799  11.10791226   0.        ]
[[ 0.56315108  0.47075236  0.21048385 -0.20905194 -0.54176992  0.        ]
 [-0.41340976  0.43516848 -0.2705033   0.65741791 -0.34299194  0.        ]
 [-0.01610124  0.3521848   0.06041477 -0.10358394 -0.12647571  0.        ]
 [ 0.0983258   0.61608668  0.18104971  0.08982656  0.74297194  0.        ]
 [-0.64612044  0.26865076 -0.03115107 -0.67993212 -0.08354581  0.        ]
 [ 0.29078244  0.11511159 -0.91931241 -0.20739948  0.117723    0.        ]]
[[ 5.19441072e+02 -5.22995872e-07  8.08618541e-15  9.89013046e-15 -2.12745626e-14  0.00000000e+00]
 [-5.22995831e-07  4.30536893e+02 -1.00725402e-14 -4.95946910e-15  1.63482408e-14  0.00000000e+00]
 [ 4.40001506e-29 -4.64887654e-29  1.81899464e+02 -2.52328839e-14 -2.55365217e-15  0.00000000e+00]
 [ 1.16434675e-28 -4.56309595e-29 -1.30336678e-28  5.80178780e+01  3.08175447e-14  0.00000000e+00]
 [-1.08603082e-27  7.16511264e-28 -4.67334454e-29  2.22238387e-28  1.1107

In [6]:
#singular values
sigma_A2 = []
eig_val = eig_val_A2
for i in range(len(eig_val)):
    sigma_A2.append(np.sqrt(eig_val[i]))
    
print(sigma_A2)

[22.79124957006931, 20.749380546514107, 13.486942604728664, 7.616864082007789, 3.332853237652959]


In [7]:
Sigma = np.sqrt(eig_val_A2) * np.eye(len(sigma_A2))
print(Sigma)
# V = [v1,v2]
V = eig_vec_A2
V = np.array(V)
print(V)
print(V.T)

[[22.79124957  0.          0.          0.          0.        ]
 [ 0.         20.74938055  0.          0.          0.        ]
 [ 0.          0.         13.4869426   0.          0.        ]
 [ 0.          0.          0.          7.61686408  0.        ]
 [ 0.          0.          0.          0.          3.33285324]]
[[ 0.11369695 -0.63430113 -0.2474224  -0.7169717   0.0973079 ]
 [ 0.70593347 -0.26774727  0.29510236  0.31405873  0.49421761]
 [-0.24584793 -0.64915281 -0.31234792  0.6152817  -0.205004  ]
 [-0.00813346  0.28177891 -0.76961917  0.09176382  0.56550882]
 [-0.65438794 -0.15866556  0.40227089 -0.01807034  0.62004295]]
[[ 0.11369695  0.70593347 -0.24584793 -0.00813346 -0.65438794]
 [-0.63430113 -0.26774727 -0.64915281  0.28177891 -0.15866556]
 [-0.2474224   0.29510236 -0.31234792 -0.76961917  0.40227089]
 [-0.7169717   0.31405873  0.6152817   0.09176382 -0.01807034]
 [ 0.0973079   0.49421761 -0.205004    0.56550882  0.62004295]]


In [8]:
Sigma_V = Sigma.dot(V.T)
print(Sigma_V)

U = A.dot(np.linalg.pinv(Sigma_V))
print(U)

A = U.dot(Sigma).dot(V.T)
print(A)

print(B)

[[  2.59129562  16.08910591  -5.60318148  -0.18537178 -14.91431895]
 [-13.16135548  -5.55558993 -13.4695186    5.84673791  -3.29221206]
 [ -3.33697169   3.98002857  -4.21261852 -10.37980954   5.42540435]
 [ -5.46107595   2.39214268   4.68651705   0.69895257  -0.13763933]
 [  0.32431295   1.64715476  -0.68324825   1.88475791   2.06651214]]
[[ 0.56315085  0.47075267 -0.21048595  0.2090496   0.54176981]
 [-0.41340959  0.4351693   0.27051705 -0.65740805  0.34299217]
 [-0.01610146  0.35218467 -0.06041617  0.10358279  0.12647566]
 [ 0.09832566  0.61608723 -0.18104705 -0.08982821 -0.74297184]
 [-0.6461212   0.26864861  0.03113633  0.67992517  0.08354552]
 [ 0.29078141  0.11510869  0.91930331  0.20740343 -0.11772315]]
[[-5.00000000e+00  7.00000000e+00 -8.00000000e+00  6.00000000e+00 -1.00000000e+01]
 [-4.00000000e+00 -9.00000000e+00 -8.00000000e+00 -1.77344553e-15  7.00000000e+00]
 [-5.00000000e+00 -2.00000000e+00 -4.00000000e+00  3.00000000e+00 -1.00000000e+00]
 [-7.00000000e+00 -4.00000000e+

In [9]:
# # Normalize vectors
# # CV = CV.T
# print(CV)

# row,col = CV.shape

# for i in range(row):
#     CV[i] = CV[i]/(np.linalg.norm(CV[i]) + 1e-15)
    
# print(CV)

In [10]:
# # Solve for U
# print(Sigma)
# U = CV.dot(np.linalg.pinv(Sigma))
# U1 = U
# print(U1)
# # print(V)
# # print(V.T)