In [1]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA

In [2]:
def QR(span): 
    
    # Copy matrix
    A1 = span
    
    # Size of array
    row,col = span.shape
    
    # Setup arrays
    # Original Values
    vector = []
    # Normalized Values
    vec_norm = []
    
    # First Column
    v1 = span[:,0]
    vec_1 = v1
#     print(vec_1)
    vector.append(vec_1)

    # Test
    v1_scale = np.square(np.linalg.norm(vec_1))
#     print(v1_scale)

    v1 = np.multiply(1/np.sqrt(v1_scale),vec_1)
#     print(v1)
    vec_norm.append(v1)     

    # Subsequent Columns

    start = 1
    end = col

    for i in range(start,end):
        
        # Initialize vectors
        length = []
        projection = []
        project = []

        # Columns
        v = span[:,i]

        for i in vector:
            leng = np.dot(i,v)
            length.append(leng)
            proj_0 = np.dot(i,i)
            projection.append(proj_0)
            proj_1 = leng/(proj_0 + 1e-15)
            project.append(proj_1)

#         print(length)
#         print(projection)
#         print(project)
        
        # Factorization
        a = min(projection)
#         print('a:',a)

        # QR equation
        vec_0 = 0
        vec_1 = np.multiply(a,v)
        for i in range(len(vector)):
            vec_0 = vec_0 - np.multiply(project[i]*a,vector[i])

        vect_0 = vec_1 + vec_0    
#         print(vect_0)
        vector.append(vect_0)

        # Scaling vector    
        # Scale
        v_scale = np.square(np.linalg.norm(vect_0))
#         print(v_scale)

        v_norm = np.multiply(1/np.sqrt(v_scale + 1e-15),vect_0)
#         print(v_norm)

        v = v_norm
        vec_norm.append(v_norm)
#         print('v norm:', v_norm)
#         print('\n')
#         print(vector)
#         print('\n')
#         print(vec_norm)
#         print('\n')
#         print(np.array(vec_norm).T)
        
    # Calculate R
    # Q matrix
    Q = vec_norm
    Q = np.array(Q)
    # A1 = np.multiply(1,A1)
    R = np.dot(Q,A1)
#     print(R)
    
    return Q.T,R


In [3]:
def QR_Givens(A):
    # Initialize G list
    G_lst = []
    Q = np.eye(row)
    
    for j in range(0,row-1):
        for i in range(j+1,row):
            # Initialize Given Rotation Matrix
            G = np.eye(row)

            # Initialize variables
            x = A[j,j]
            y = A[i,j]
            r = np.sqrt(x**2 + y**2)

            r1 = np.linalg.norm(A[j:i,j])

            cos_t = x/r
            sin_t = y/r

            G[j,j] = cos_t
            G[j,i] = sin_t
            G[i,j] = -sin_t
            G[i,i] = cos_t

            G_lst.append(G)

            Q = np.dot(Q,G)

            A = np.dot(G,A)
            
    #Q
    G_lst_len = len(G_lst)
    G_lst = np.array(G_lst)
    # Q_mat = np.dot(G1.T,np.dot(G2.T,G3.T))
    Q_mat = G_lst[0].T
    for i in range(1,G_lst_len):
    #     print(Q_mat)
        Q_mat = Q_mat.dot(G_lst[i].T)
#     print(Q_mat)

    return Q_mat,A

 

In [4]:
def QR_eig(A):
    pQ = np.eye(A.shape[0])
#     print('pQ:',pQ)
    X=A.copy()
    for i in range(100):
            Q,R = QR_Givens(X)
            pQ = pQ.dot(Q)
            X = R.dot(Q)
            
                
    return pQ,X

In [5]:
row = 4
col = 2
A = np.random.randint(10,size=(row,col))
print('A:',A)

# A = np.array([[2,4],[1,3],[0,0],[0,0]])
# A = np.array([[2,1,0],[1,3,1],[0,1,4]])
# W = A.dot(A.T)
row,col = A.shape
if row == col:
    W = A.copy()
else:
    W = A.dot(A.T)
print(W)

A: [[2 6]
 [5 4]
 [9 6]
 [1 0]]
[[ 40  34  54   2]
 [ 34  41  69   5]
 [ 54  69 117   9]
 [  2   5   9   1]]


In [6]:
# W = W.dot(W.T)
eigen_vec,eigen_val = QR_eig(W)
print(eigen_val)
print('\n')
print(eigen_vec)

r,c = A.shape
print(r,c)

idty = np.eye(r)
print(idty)

# for i in range(c):
#     for j in range(r):
#         idty[j,i] = eigen_vec[j,i]

print(idty)

[[ 1.86265489e+002  2.02366220e-014 -1.76144708e-015 -2.91282919e-015]
 [ 1.18820332e-114  1.27345115e+001  2.98270585e-015 -3.89763536e-016]
 [-1.33397724e-322  2.47032823e-323  1.80644977e-015 -8.60761285e-016]
 [ 4.94065646e-324 -9.88131292e-324 -2.53336972e-074 -4.69204859e-016]]


[[ 0.39980529 -0.89613405  0.13136921  0.1408603 ]
 [ 0.4687071   0.07926724 -0.87977241 -0.00555511]
 [ 0.78576667  0.39572857  0.45514573 -0.13715689]
 [ 0.05513734  0.1845518   0.03981208  0.98046698]]
4 2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
w,v = np.linalg.eig(W)
print(w)
print(v)

[ 1.86265489e+02  1.27345115e+01 -1.06773397e-14 -2.64329018e-16]
[[-0.39980529  0.89613405  0.14135784 -0.09654697]
 [-0.4687071  -0.07926724 -0.87780531 -0.25064282]
 [-0.78576667 -0.39572857  0.4438457   0.26364218]
 [-0.05513734 -0.1845518   0.11169955 -0.92647162]]


In [8]:
import scipy.linalg as la
eigvals, eigvecs = la.eig(W)
print(eigvals.real)
print(eigvecs)


[ 1.86265489e+02  1.27345115e+01 -1.06773397e-14 -2.64329018e-16]
[[-0.39980529  0.89613405  0.14135784 -0.09654697]
 [-0.4687071  -0.07926724 -0.87780531 -0.25064282]
 [-0.78576667 -0.39572857  0.4438457   0.26364218]
 [-0.05513734 -0.1845518   0.11169955 -0.92647162]]


In [9]:
# a = np.array([[0, 2], 
#               [2, 3]])
a = b = W.copy()
p = [1, 5, 10, 20]
for i in range(20):
    q, r = np.linalg.qr(a)
    a = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(a)

Iteration 1:
[[ 1.82284003e+02  2.59818952e+01  0.00000000e+00 -7.10542736e-15]
 [ 2.59818952e+01  1.67159972e+01 -1.77635684e-15  0.00000000e+00]
 [ 2.58279416e-15  1.96318787e-15  1.65384749e-15 -2.41955373e-16]
 [-1.35702348e-17 -9.75209816e-17 -1.40608365e-17  5.01416449e-16]]
Iteration 5:
[[ 1.86265489e+02  5.80966271e-04 -3.03476645e-15 -7.03239861e-15]
 [ 5.80966271e-04  1.27345115e+01 -3.31907097e-15  1.13061856e-15]
 [ 1.63335906e-83  4.48412778e-79  1.65676928e-15 -2.28010316e-16]
 [-7.05871078e-88 -2.22021506e-82 -1.15779377e-19  4.98494661e-16]]
Iteration 10:
[[ 1.86265489e+002  8.67742195e-010 -3.03407634e-015  7.03269739e-015]
 [ 8.67761514e-010  1.27345115e+001 -3.31917353e-015 -1.13031116e-015]
 [ 9.09399854e-169  1.67163043e-158  1.65679201e-015  2.27894822e-016]
 [ 9.68891631e-176  2.04030642e-164  2.85437808e-022  4.98471926e-016]]
Iteration 20:
[[ 1.86265489e+002 -1.93191437e-014 -3.03407461e-015  7.03269814e-015]
 [ 1.93597309e-021  1.27345115e+001 -3.31917381e-015

In [10]:
def normalize(x):
    fac = abs(x).max()
    x_n = x / x.max()
    return fac, x_n

In [11]:
x = np.diag(eigen_val)
a = b

for i in range(100):
    x = np.dot(a, x)
    lambda_1, x = normalize(x)
    
print(lambda_1)
print(x)

186.26548853086695
[0.50880918 0.59649655 1.         0.07017012]


In [12]:
# power iteration / von Mises iteration
# gives an approximation for an eigenvector for the dominant eigenvalue of a matrix A
# by doing the power iteration k times
def power_iteration(A, k: int):
    v = np.random.rand(A.shape[1])

    for _ in range(k):
        # calculates b = Av
        b = np.dot(A, v)

        # calculate the norm of b
        b_norm = np.linalg.norm(b)

        # define v to be the normalized version of b
        v = b / b_norm

    return v

def give_eigenvalue(A,k):
    v=power_iteration(A,k)
    lam = np.dot(A,v)[0]/v[0]
    
    return lam

In [13]:
v=power_iteration(b,3)
v

array([0.39981287, 0.46870643, 0.78576332, 0.05513578])