In [1]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA

In [2]:
A = np.array([[1,2,3,4],[2,1,2,2],[3,2,1,3],[4,2,3,1]])
print(A)

[[1 2 3 4]
 [2 1 2 2]
 [3 2 1 3]
 [4 2 3 1]]


In [3]:
# Shape
n,m = A.shape

In [4]:
for i in range(0,n-1):
    x = A[i+1:n,i]
    x1 = np.dot(-np.sign(A[i+1,i]),np.sqrt(np.dot(x.T,x)))
    u = np.zeros((n-i-1,1))
    u[0] = np.sqrt((x1-x[0])/(2*x1))
    for j in range(1,n-i-1):
        u[j] = x[j]/(-2*u[0]*x1)

    H = np.eye(n)
    H[i+1:n,i+1:n] = H[i+1:n,i+1:n] - np.dot(2,np.dot(u,u.T))
    print(H)
    A = np.dot(H.T,np.dot(A,H))
    print(A)
A


[[ 1.          0.          0.          0.        ]
 [ 0.         -0.37139068 -0.55708601 -0.74278135]
 [ 0.         -0.55708601  0.77370064 -0.30173248]
 [ 0.         -0.74278135 -0.30173248  0.59769003]]
[[ 1.00000000e+00 -5.38516481e+00  0.00000000e+00 -1.11022302e-16]
 [-5.38516481e+00  5.41379310e+00 -1.22091698e-01  1.38467222e+00]
 [ 0.00000000e+00 -1.22091698e-01 -1.45241113e+00  6.29541008e-01]
 [-1.11022302e-16  1.38467222e+00  6.29541008e-01 -9.61381978e-01]]
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.         -0.08783295  0.99613522]
 [ 0.          0.          0.99613522  0.08783295]]
[[ 1.00000000e+00 -5.38516481e+00 -1.10593226e-16 -9.75141585e-18]
 [-5.38516481e+00  5.41379310e+00  1.39004444e+00  5.41233725e-16]
 [-1.10593226e-16  1.39004444e+00 -1.07533156e+00  6.62789515e-01]
 [-9.75141585e-18  9.71445147e-17  6.62789515e-01 -1.33846154e+00]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. 

array([[ 1.00000000e+00, -5.38516481e+00, -1.10593226e-16,  9.75141585e-18],
       [-5.38516481e+00,  5.41379310e+00,  1.39004444e+00, -5.41233725e-16],
       [-1.10593226e-16,  1.39004444e+00, -1.07533156e+00, -6.62789515e-01],
       [ 9.75141585e-18, -9.71445147e-17, -6.62789515e-01, -1.33846154e+00]])

In [5]:
def hess(A):
    
    # Shape
    n,m = A.shape
    
    for i in range(0,n-1):
        x = A[i+1:n,i]
        x1 = np.dot(-np.sign(A[i+1,i]),np.sqrt(np.dot(x.T,x)))
        u = np.zeros((n-i-1,1))
        u[0] = np.sqrt((x1-x[0])/(2*x1))
        for j in range(1,n-i-1):
            u[j] = x[j]/(-2*u[0]*x1)

        H = np.eye(n)
        H[i+1:n,i+1:n] = H[i+1:n,i+1:n] - np.dot(2,np.dot(u,u.T))
        print(H)
        A = np.dot(H.T,np.dot(A,H))
        print(A)

    return A


In [6]:
A = np.array([[1,2,3,4],[2,1,2,2],[3,2,1,3],[4,2,3,1]])
A = hess(A)
print(A)

[[ 1.          0.          0.          0.        ]
 [ 0.         -0.37139068 -0.55708601 -0.74278135]
 [ 0.         -0.55708601  0.77370064 -0.30173248]
 [ 0.         -0.74278135 -0.30173248  0.59769003]]
[[ 1.00000000e+00 -5.38516481e+00  0.00000000e+00 -1.11022302e-16]
 [-5.38516481e+00  5.41379310e+00 -1.22091698e-01  1.38467222e+00]
 [ 0.00000000e+00 -1.22091698e-01 -1.45241113e+00  6.29541008e-01]
 [-1.11022302e-16  1.38467222e+00  6.29541008e-01 -9.61381978e-01]]
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.         -0.08783295  0.99613522]
 [ 0.          0.          0.99613522  0.08783295]]
[[ 1.00000000e+00 -5.38516481e+00 -1.10593226e-16 -9.75141585e-18]
 [-5.38516481e+00  5.41379310e+00  1.39004444e+00  5.41233725e-16]
 [-1.10593226e-16  1.39004444e+00 -1.07533156e+00  6.62789515e-01]
 [-9.75141585e-18  9.71445147e-17  6.62789515e-01 -1.33846154e+00]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. 