In [16]:
from typing import List, Dict, Iterable, Tuple, Callable
from matplotlib import pyplot as plt
from collections import Counter
import sys
import os
import string
import urllib.request
import requests
import curl
import pycurl
import webbrowser
import numpy as np
import math
import pandas as pd
# from IPython import qt
from matplotlib.pyplot import figure
from py.xml import raw
from requests.api import get
from matplotlib import pyplot as plt
# from scratch.working_with_data import rescale
# from scratch.multiple_regression import least_squares_fit, predict
# from scratch.gradient_descent import gradient_step

# from stats import mean, median, de_mean, standard_deviation, correlation
# from gradient_descent import minimize_stochastic, maximize_stochastic, maximize_batch
# from vector import dot, vector_add
# from normal import normal_cdf
# from matrix import make_matrix, get_column, shape, matrix_multiply
# from logistic_regression import *

import math
import os
import random
import sys
from functools import partial, reduce

from scipy.optimize import fmin_tnc

import itertools
import random
import tqdm


from typing import*

from collections import*
# from scipy import*
from sklearn.metrics import*

from numpy import *

# bltin_sum = np.sum

import random

from itertools import cycle
from sklearn import*
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score

In [17]:
class LogisticRegression(object):
    def __init__(self, eta=0.1, n_iter=50):
        self.eta = eta
        self.n_iter = n_iter

    def fit(self, X, y):
        X = np.insert(X, 0, 1, axis=0)
        self.w = np.ones(X.shape[1])
#         self.w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
        m = X.shape[0]

        for _ in range(self.n_iter):
            output = X.dot(self.w)
            errors = y - self._sigmoid(output)
            self.w += self.eta / m * errors.dot(X)
        return self

    def predict(self, X):
        output = np.insert(X, 0, 1, axis=1).dot(self.w)
        return (np.floor(self._sigmoid(output) + .5)).astype(int)

    def score(self, X, y):
        return sum(self.predict(X) == y) / len(y)

    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

In [18]:
# class LogisticRegression(object):
#     def __init__(self, eta=0.1, n_iter=50):
#         self.eta = eta
#         self.n_iter = n_iter

#     def fit(self, X, y):
#         X = np.insert(X, 0, 1, axis=1)
#         self.w = np.ones(X.shape[1])
# #         self.w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
#         m = X.shape[0]

#         for _ in range(self.n_iter):
#             output = X.dot(self.w)
#             errors = y - self._sigmoid(output)
#             self.w += self.eta / m * errors.dot(X)
#         return self

#     def predict(self, X):
#         output = np.insert(X, 0, 1, axis=1).dot(self.w)
#         return (np.floor(self._sigmoid(output) + .5)).astype(int)

#     def score(self, X, y):
#         return sum(self.predict(X) == y) / len(y)

#     def _sigmoid(self, x):
#         return 1 / (1 + np.exp(-x))

In [19]:
# import requests
# import csv

# rows = []

# filename = 'iris.csv'
# # reading csv file 
# with open(filename, 'r') as csvfile: 
#     # creating a csv reader object 
#     csvreader = csv.reader(csvfile) 
# #     iris_data = [parse_iris_row(row) for row in csvreader]

# # extracting each data row one by one
#     for row in csvreader: 
#         rows.append(row) 

In [20]:
# X = np.array([[-2, 2],[-3, 0],[2, -1],[1, -4]])
# y = np.array([1,1,0,0])
# logi = LogisticRegression().fit(X, y)
# print(logi.predict(X))

In [21]:
# type(X)

In [22]:
# X = np.array([[-2],[-3],[2],[1]])
# y = np.array([1,1,0,0])
# logi = LogisticRegression().fit(X, y)
# print(logi.predict(X))

In [23]:
import requests
import csv

# rows = []

# filename = 'MergedLabeled.csv'
# # reading csv file 
# with open(filename, 'r') as csvfile: 
#     # creating a csv reader object 
#     csvreader = csv.reader(csvfile) 
    
# #     csvreader.to_csv(filename, header=False, index=False)
# #     iris_data = [parse_iris_row(row) for row in csvreader]

# # extracting each data row one by one
#     for row in csvreader: 
#         rows.append(row) 
        
# MergedLabels = pd.DataFrame(rows)

df_loans_full = pd.read_csv('MergedLabeled.csv', header = None, skiprows=1)
df_loans_full

0       1      2           3                  4   5      6   \
0         1   20122  33152  2014-12-08  debtconsolidation   0  15405   
1         2   20344  53857  2016-06-19    homeimprovement   0  28529   
2         3   22077  64998  2014-06-29  debtconsolidation   0  14113   
3         4   22581  84947  2015-05-18  debtconsolidation   0  21204   
4         5   25176  60208  2014-11-30  debtconsolidation   0  20893   
...     ...     ...    ...         ...                ...  ..    ...   
9995   9996   94170  53633  2016-01-05    homeimprovement   0  18936   
9996   9997   99570  62115  2014-08-22  debtconsolidation   0  22797   
9997   9998  102795  55718  2015-05-25    homeimprovement   0  25104   
9998   9999  103509  74249  2016-06-16  debtconsolidation   0  17143   
9999  10000  106342  16614  2014-05-27  debtconsolidation   0  18335   

             7      8     9   ...  20  21     22         23  24  25  26  27  \
0     48 months   9.52   387  ...   9   7  16314  54.000000   0   1   1   0   
1     36 months  17.90  1030  ...  10   5  14600  48.840000   0   0   0   3   
2     36 months  15.61   493  ...  15  13  13665  83.949997   0   0   0   0   
3     60 months   5.95   409  ...   7   6  10344  77.010002  11   0   0   0   
4     60 months   8.25   426  ...  14  14  19694  70.260002   0  13   9   2   
...         ...    ...   ...  ...  ..  ..    ...        ...  ..  ..  ..  ..   
9995  60 months   9.61   399  ...  19  16  14525  87.629997   2   0   0   1   
9996  60 months   7.37   455  ...   7   3  15919  49.400002   0   0   0   0   
9997  36 months   7.93   786  ...  11  10  15735  50.680000   0   0   0   0   
9998  48 months   5.37   398  ...  15   8  13002  59.560001   0   0   0   1   
9999  36 months  10.66   597  ...  10   6  14759  64.080002   0   8   4   1   

      28          29  
0      0  1026398210  
1      0  -868996371  
2      0  -389639751  
3      0  1240408668  
4      0  1220269697  
...   ..         ...  
9995   0 -1870257149  
9996   0  1857008161  
9997   0 -1911701526  
9998   0  2076012910  
9999   0  1129730475  

[10000 rows x 30 columns]

In [24]:
# label = df_loans_full.iloc[0,7]
# # label
# label = label[:2].split(" ")[-1]
# label

for i in range(len(df_loans_full[7])):
    label = df_loans_full.iloc[i,7]
    label = label[:2].split(" ")[-1]    
    df_loans_full.iloc[i,7] = label

In [25]:
# Select columns
# col = [6,7,8,9,15,16,17,18,19,20,21,22,23,24,25,26,27]
col = [6,7,8,9,15,16,17,18,19]
df_loans = df_loans_full.iloc[:,[6,8]]
df_loans


6      8
0     15405   9.52
1     28529  17.90
2     14113  15.61
3     21204   5.95
4     20893   8.25
...     ...    ...
9995  18936   9.61
9996  22797   7.37
9997  25104   7.93
9998  17143   5.37
9999  18335  10.66

[10000 rows x 2 columns]

In [26]:
df_isbad = df_loans_full.iloc[:,28]
df_isbad

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: 28, Length: 10000, dtype: int64

In [27]:
loans = df_loans.to_numpy()
pred = df_isbad.to_numpy()
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
loans = loans.reshape(10000,2)
pred = pred.reshape(10000,1)
loans

array([[1.54050000e+04, 9.52000046e+00],
       [2.85290000e+04, 1.78999996e+01],
       [1.41130000e+04, 1.56099997e+01],
       ...,
       [2.51040000e+04, 7.92999983e+00],
       [1.71430000e+04, 5.36999989e+00],
       [1.83350000e+04, 1.06599998e+01]])

In [29]:
# logi = LogisticRegression().fit(loans.T,pred)

In [30]:
pred


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)