In [1067]:
import sympy as sym
import numpy as num
import matplotlib.pyplot as pyplot

import sympy as sy
import numpy as np
from sympy.functions import sin,cos,exp
import matplotlib.pyplot as plt
from sympy import* 
import math
plt.style.use("ggplot")

pyplot.style.use("ggplot")

In [1068]:
x = 0
h = 0.001
n = 4
term = 3
# f = lambda x: np.exp(x)

In [1069]:
# Create list of zeros
mat_list = np.matrix(np.zeros((n,n)))
m = floor(n/2)
print(m)
# First half
print(n)
for i in range(m):
#     print(i)
    for j in range(n):
        mat_list[j,i] = ((m-i)**j)
        mat_list[j,i + m] = ((i)**j)*(-1)**j

# Middle function
mat_list[0,m] = 1
print(mat_list)

2
4
[[ 1.  1.  1.  1.]
 [ 2.  1.  0. -1.]
 [ 4.  1.  0.  1.]
 [ 8.  1.  0. -1.]]


In [1070]:
for i in range(0,4):
    print(1/math.factorial(i+1)*(-1)**(i+1))

-1.0
0.5
-0.16666666666666666
0.041666666666666664


In [1071]:
# Create list of zeros
n = 6
mat_list = np.matrix(np.zeros((n,n)))
print(mat_list)
# m = floor(n/2)
m = 2
print(m)
for j in range(m): 
    for i in range(1,n+1):
        mat_list[i-1,3*j] = ((m**(i))/math.factorial(i)) 
        mat_list[i-1,3*j-2]=(1/math.factorial(i+1))
        if j > (m/2 - 1):
            mat_list[i-1,3*j] = ((m**(i))/math.factorial(i))*(-1)**(i+1)
            mat_list[i-1,3*j-1]=(1/math.factorial(i+1)) * (-1)**(i+1)            
print(mat_list.T)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
2
[[ 2.00000000e+00  2.00000000e+00  1.33333333e+00  6.66666667e-01
   2.66666667e-01  8.88888889e-02]
 [ 5.00000000e-01  1.66666667e-01  4.16666667e-02  8.33333333e-03
   1.38888889e-03  1.98412698e-04]
 [ 5.00000000e-01 -1.66666667e-01  4.16666667e-02 -8.33333333e-03
   1.38888889e-03 -1.98412698e-04]
 [ 2.00000000e+00 -2.00000000e+00  1.33333333e+00 -6.66666667e-01
   2.66666667e-01 -8.88888889e-02]
 [ 5.00000000e-01  1.66666667e-01  4.16666667e-02  8.33333333e-03
   1.38888889e-03  1.98412698e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]


In [1072]:
# Index
print(term)
b = np.zeros((1,n))
# b[0][term-1] = math.factorial(term-1)/(h**(term-1))
b[0][term-1] = math.factorial(term-1)
print(b)
# Weights
c = np.linalg.pinv(mat_list)*b.T
print(c)


3
[[0. 0. 2. 0. 0. 0.]]
[[ 0.81602424]
 [-1.62866621]
 [-3.25733243]
 [ 0.81602424]
 [-1.62866621]
 [ 0.        ]]


In [1073]:
# Create list of zeros
n = 5
mat_list = np.matrix(np.zeros((n,n)))
m = floor(n/2)
print(m)
# First half
print(n)
for i in range(m+1):
#     print(i)
    for j in range(n):
        mat_list[j,i] = ((m-i)**j)/math.factorial(j)
        mat_list[j,i + m] = ((i)**j)*(-1)**j/math.factorial(j)

# Middle function
mat_list[0,m] = 1
print(mat_list)

2
5
[[ 1.          1.          1.          1.          1.        ]
 [ 2.          1.          0.         -1.         -2.        ]
 [ 2.          0.5         0.          0.5         2.        ]
 [ 1.33333333  0.16666667  0.         -0.16666667 -1.33333333]
 [ 0.66666667  0.04166667  0.          0.04166667  0.66666667]]


In [1074]:
# Index
print(term)
b = np.zeros((1,n))
# b[0][term-1] = math.factorial(term-1)/(h**(term-1))
# b[0][term-1] = math.factorial(term-1)
b[0][4] = math.factorial(1)
print(b)
# Weights
c = np.linalg.pinv(mat_list)*b.T
print(c)


3
[[0. 0. 0. 0. 1.]]
[[ 1.]
 [-4.]
 [ 6.]
 [-4.]
 [ 1.]]


In [1075]:
# f_0 = 'x**3 + x - 1'
# f_1 = str(f_0)
f = lambda x: np.sin(x)

In [1076]:
i = 1
h = 0.001
# a = terms
func = np.matrix([f(i-2*h),f(i-h),f(i),f(i+h),(f(i+2*h))])/(h**4)
print(func)

[[8.40388698e+11 8.40930262e+11 8.41470985e+11 8.42010866e+11
  8.42549906e+11]]


In [1077]:
for i in range(5):
    deriv = np.matmul(func,c)/math.factorial(i)
    print(deriv)

[[0.84545898]]
[[0.84545898]]
[[0.42272949]]
[[0.14090983]]
[[0.03522746]]
