In [53]:
import sympy as sym
import numpy as num
import matplotlib.pyplot as pyplot

import sympy as sy
import numpy as np
from sympy.functions import sin,cos,exp
import matplotlib.pyplot as plt
from sympy import* 
import math
plt.style.use("ggplot")

pyplot.style.use("ggplot")

In [54]:
x = 0
h = 0.001
n = 4
term = 3
# f = lambda x: np.exp(x)

In [55]:
# Create list of zeros
mat_list = np.matrix(np.zeros((n,n)))
m = floor(n/2)
print(m)
# First half
print(n)
for i in range(m):
#     print(i)
    for j in range(n):
        mat_list[j,i] = ((m-i)**j)
        mat_list[j,i + m] = ((i)**j)*(-1)**j

# Middle function
mat_list[0,m] = 1
print(mat_list)

2
4
[[ 1.  1.  1.  1.]
 [ 2.  1.  0. -1.]
 [ 4.  1.  0.  1.]
 [ 8.  1.  0. -1.]]


In [56]:
for i in range(0,4):
    print(1/math.factorial(i+1)*(-1)**(i+1))

-1.0
0.5
-0.16666666666666666
0.041666666666666664


In [57]:
# Create list of zeros
q = 0
mat_list = np.matrix(np.zeros((n,n)))
print(mat_list)
# m = floor(n/2)
m = 2
print(m)
for j in range(m): 
    for i in range(1,n+1):
        mat_list[i-1,3*j] = ((m**(i))/math.factorial(i)) 
        mat_list[i-1,3*j-2]=(1/math.factorial(i+1))
        if j > (m/2 - 1):
            mat_list[i-1,3*j] = ((m**(i))/math.factorial(i))*(-1)**(i+1)
            mat_list[i-1,3*j-1]=(1/math.factorial(i+1)) * (-1)**(i+1)            
print(mat_list)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
[[ 2.          0.5         0.5         2.        ]
 [ 2.          0.16666667 -0.16666667 -2.        ]
 [ 1.33333333  0.04166667  0.04166667  1.33333333]
 [ 0.66666667  0.00833333 -0.00833333 -0.66666667]]


In [58]:
# Index
print(term)
b = np.zeros((1,n))
# b[0][term-1] = math.factorial(term-1)/(h**(term-1))
b[0][term-1] = math.factorial(term-1)
print(b)
# Weights
c = np.linalg.pinv(mat_list)*b.T
print(c)


3
[[0. 0. 2. 0.]]
[[ 0.85714286]
 [-3.42857143]
 [-3.42857143]
 [ 0.85714286]]


In [59]:
# Create list of zeros
n = 7
mat_list = np.matrix(np.zeros((n,n)))
m = floor(n/2)
print(m)
# First half
print(n)
for i in range(m+1):
#     print(i)
    for j in range(n):
        mat_list[j,i] = ((m-i)**j)/math.factorial(j)
        mat_list[j,i + m] = ((i)**j)*(-1)**j/math.factorial(j)

# Middle function
mat_list[0,m] = 1
print(mat_list.T)

3
7
[[ 1.00000000e+00  3.00000000e+00  4.50000000e+00  4.50000000e+00
   3.37500000e+00  2.02500000e+00  1.01250000e+00]
 [ 1.00000000e+00  2.00000000e+00  2.00000000e+00  1.33333333e+00
   6.66666667e-01  2.66666667e-01  8.88888889e-02]
 [ 1.00000000e+00  1.00000000e+00  5.00000000e-01  1.66666667e-01
   4.16666667e-02  8.33333333e-03  1.38888889e-03]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  5.00000000e-01 -1.66666667e-01
   4.16666667e-02 -8.33333333e-03  1.38888889e-03]
 [ 1.00000000e+00 -2.00000000e+00  2.00000000e+00 -1.33333333e+00
   6.66666667e-01 -2.66666667e-01  8.88888889e-02]
 [ 1.00000000e+00 -3.00000000e+00  4.50000000e+00 -4.50000000e+00
   3.37500000e+00 -2.02500000e+00  1.01250000e+00]]


In [60]:
# Index
print(term)
b = np.zeros((1,n))
# b[0][term-1] = math.factorial(term-1)/(h**(term-1))
# b[0][term-1] = math.factorial(term-1)
b[0][4] = math.factorial(3)
print(b)
# Weights
c = np.linalg.pinv(mat_list)*b.T
print(c)


3
[[0. 0. 0. 0. 6. 0. 0.]]
[[ -1.]
 [ 12.]
 [-39.]
 [ 56.]
 [-39.]
 [ 12.]
 [ -1.]]


In [61]:
# f_0 = 'x**3 + x - 1'
# f_1 = str(f_0)
f = lambda x: np.sin(x)

In [62]:
i = 0
h = 0.001
# a = terms
func = np.matrix([f(i+3*h),f(i+2*h),f(i+h),f(i),f(i-h),f(i-2*h),f(i-3*h)])/(h**4)
print(func)

[[ 2.99999550e+09  1.99999867e+09  9.99999833e+08  0.00000000e+00
  -9.99999833e+08 -1.99999867e+09 -2.99999550e+09]]


In [63]:
for i in range(5):
    deriv = np.matmul(func,c)/math.factorial(i)
    print(deriv)

[[1.52587891e-05]]
[[1.52587891e-05]]
[[7.62939453e-06]]
[[2.54313151e-06]]
[[6.35782878e-07]]


In [64]:
# Create list of zeros
n = 4
mat_list = np.zeros((n,int(n/2)))
mat_list_2 = np.zeros((n,int(n/2)))
m = int(n/2)
print(m)
# First half
print(n)

# First Half
for i in reversed(range(m)):
    for j in range(n):
    #     mat_list[j,0] = ((m-i)**j)/math.factorial(j)
        mat_list[j,i] = ((m-i)**j)/math.factorial(j)
print(mat_list)

# Second Half
for i in range(m):
    for j in range(n):
    #     mat_list[j,0] = ((m-i)**j)/math.factorial(j)
        mat_list_2[j,i] = ((m-i)**j)*(-1)**j/math.factorial(j)
# mat_list_2[:,[0,1]] = mat_list_2[:,[1,0]]

print(mat_list_2)

# Concatenate 
mat_list_final = np.hstack((mat_list,np.flip(mat_list_2,1)))
print(mat_list_final)

2
4
[[1.         1.        ]
 [2.         1.        ]
 [2.         0.5       ]
 [1.33333333 0.16666667]]
[[ 1.          1.        ]
 [-2.         -1.        ]
 [ 2.          0.5       ]
 [-1.33333333 -0.16666667]]
[[ 1.          1.          1.          1.        ]
 [ 2.          1.         -1.         -2.        ]
 [ 2.          0.5         0.5         2.        ]
 [ 1.33333333  0.16666667 -0.16666667 -1.33333333]]


In [65]:
# Index
print(term)
b = np.zeros((1,4))
# print(b)
# b[0][term-1] = math.factorial(term-1)/(h**(term-1))
# b[0][term-1] = math.factorial(term-1)
b[0][1] = 12
print(b)
# Weights
c = np.linalg.pinv(np.matrix(mat_list_final))*b.T
print(c)


3
[[ 0. 12.  0.  0.]]
[[-1.]
 [ 8.]
 [-8.]
 [ 1.]]


In [66]:
# Create list of zeros
n = 5
mat_list = np.matrix(np.zeros((n,n)))
m = floor(n/2)
print(m)
# First half
print(n)
for i in range(m+1):
#     print(i)
    for j in range(n):
        mat_list[j,i] = ((m-i)**j)/math.factorial(j)
        mat_list[j,i + m] = ((i)**j)*(-1)**j/math.factorial(j)

# Middle function
mat_list[0,m] = 1
print(mat_list)

2
5
[[ 1.          1.          1.          1.          1.        ]
 [ 2.          1.          0.         -1.         -2.        ]
 [ 2.          0.5         0.          0.5         2.        ]
 [ 1.33333333  0.16666667  0.         -0.16666667 -1.33333333]
 [ 0.66666667  0.04166667  0.          0.04166667  0.66666667]]


In [67]:
# Index
print(term)
b = np.zeros((1,n))
# b[0][term-1] = math.factorial(term-1)/(h**(term-1))
# b[0][term-1] = math.factorial(term-1)
b[0][2] = 12
print(b)
# Weights
c = np.linalg.pinv(mat_list)*b.T
print(c)


3
[[ 0.  0. 12.  0.  0.]]
[[ -1.]
 [ 16.]
 [-30.]
 [ 16.]
 [ -1.]]


In [68]:
# Create list of zeros
n = 6
mat_list = np.zeros((n,int(n/2)))
mat_list_2 = np.zeros((n,int(n/2)))
m = int(n/2)
print(m)
# First half
print(n)

# First Half
for i in reversed(range(m)):
    for j in range(n):
    #     mat_list[j,0] = ((m-i)**j)/math.factorial(j)
        mat_list[j,i] = ((m-i)**j)/math.factorial(j)
print(mat_list)

# Second Half
for i in range(m):
    for j in range(n-1,-1,-1):
    #     mat_list[j,0] = ((m-i)**j)/math.factorial(j)
        mat_list_2[j,i] = ((m-i)**j)*(-1)**j/math.factorial(j)
# mat_col = [0:2]
# mat_list_2[:,[0,1,2]] = mat_list_2[:,[2,1,0]]

# print(mat_list_2)
# print("\n")
# matt=np.flip(mat_list_2,1)
# print(matt)
# print(mat_list_2)

# Concatenate 
mat_list_final = np.hstack((mat_list,np.flip(mat_list_2,1)))
print(mat_list_final)

3
6
[[1.         1.         1.        ]
 [3.         2.         1.        ]
 [4.5        2.         0.5       ]
 [4.5        1.33333333 0.16666667]
 [3.375      0.66666667 0.04166667]
 [2.025      0.26666667 0.00833333]]
[[ 1.          1.          1.          1.          1.          1.        ]
 [ 3.          2.          1.         -1.         -2.         -3.        ]
 [ 4.5         2.          0.5         0.5         2.          4.5       ]
 [ 4.5         1.33333333  0.16666667 -0.16666667 -1.33333333 -4.5       ]
 [ 3.375       0.66666667  0.04166667  0.04166667  0.66666667  3.375     ]
 [ 2.025       0.26666667  0.00833333 -0.00833333 -0.26666667 -2.025     ]]


In [69]:
# Index
print(term)
b = np.zeros((1,n))
# b[0][term-1] = math.factorial(term-1)/(h**(term-1))
# b[0][term-1] = math.factorial(term-1)
b[0][3] = 8
print(b)
# Weights
c = np.linalg.pinv(np.matrix(mat_list_final))*b.T
print(c)


3
[[0. 0. 0. 8. 0. 0.]]
[[ -1.]
 [  8.]
 [-13.]
 [ 13.]
 [ -8.]
 [  1.]]


In [70]:
for i in range(3,-1,-1):
    print(i)

3
2
1
0


In [71]:
# Create list of zeros
n = 7
mat_list = np.matrix(np.zeros((n,n)))
m = floor(n/2)
print(m)
# First half
print(n)
for i in range(m+1):
#     print(i)
    for j in range(n):
        mat_list[j,i] = ((m-i)**j)/math.factorial(j)
        mat_list[j,i + m] = ((i)**j)*(-1)**j/math.factorial(j)

# Middle function
mat_list[0,m] = 1
print(mat_list.T)

3
7
[[ 1.00000000e+00  3.00000000e+00  4.50000000e+00  4.50000000e+00
   3.37500000e+00  2.02500000e+00  1.01250000e+00]
 [ 1.00000000e+00  2.00000000e+00  2.00000000e+00  1.33333333e+00
   6.66666667e-01  2.66666667e-01  8.88888889e-02]
 [ 1.00000000e+00  1.00000000e+00  5.00000000e-01  1.66666667e-01
   4.16666667e-02  8.33333333e-03  1.38888889e-03]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  5.00000000e-01 -1.66666667e-01
   4.16666667e-02 -8.33333333e-03  1.38888889e-03]
 [ 1.00000000e+00 -2.00000000e+00  2.00000000e+00 -1.33333333e+00
   6.66666667e-01 -2.66666667e-01  8.88888889e-02]
 [ 1.00000000e+00 -3.00000000e+00  4.50000000e+00 -4.50000000e+00
   3.37500000e+00 -2.02500000e+00  1.01250000e+00]]


In [72]:
# Index
print(term)
b = np.zeros((1,n))
# b[0][term-1] = math.factorial(term-1)/(h**(term-1))
# b[0][term-1] = math.factorial(term-1)
b[0][4] = math.factorial(3)
print(b)
# Weights
c = np.linalg.pinv(mat_list)*b.T
print(c)


3
[[0. 0. 0. 0. 6. 0. 0.]]
[[ -1.]
 [ 12.]
 [-39.]
 [ 56.]
 [-39.]
 [ 12.]
 [ -1.]]


In [73]:
h = 0.0001
i= 0.01
fac = 13
term = 13
f = lambda x: np.sin(x)

func = np.matrix([f(i-3*h),f(i-2*h),f(i-h),f(i),f(i+h),f(i+2*h),f(i+3*h)])/(h**4)
print(func)

sign = 2
rem = term%4
if rem == 3:
    sign = 1  
print(sign)
deriv = (np.matmul(func,c)/6/math.factorial(term)) * (-1) ** (sign)

# deriv = deriv*(h**(term-1))

print(deriv)

[[9.69984789e+13 9.79984314e+13 9.89983828e+13 9.99983333e+13
  1.00998283e+14 1.01998231e+14 1.02998179e+14]]
2
[[1.60590438e-10]]


In [74]:
h = 0.0037
# h = 0.0009000000000000002 * 6
i= 0.01
fac = 13
term = 12
f = lambda x: np.cos(x)

func = np.matrix([f(i-3*h),f(i-2*h),f(i-h),f(i),f(i+h),f(i+2*h),f(i+3*h)])/(h**4)
print(func)

sign = 1
rem = (term)%4
if rem == 0 or rem == 3:
    sign = 2    
print(sign)

deriv = (np.matmul(func,c)/6/math.factorial(term)) * (-1) ** (sign)

# deriv = deriv*(h**(term-1))

print(deriv)

[[5.33571766e+09 5.33570286e+09 5.33561500e+09 5.33545411e+09
  5.33522017e+09 5.33491319e+09 5.33453318e+09]]
2
[[2.0876757e-09]]


In [75]:
term=16
(term)%4

0

In [76]:
from sympy import*
var( 'x' )
formula = sin(x)
series(formula, x, 0, 18).removeO()

x**17/355687428096000 - x**15/1307674368000 + x**13/6227020800 - x**11/39916800 + x**9/362880 - x**7/5040 + x**5/120 - x**3/6 + x

In [77]:
tol = 1e-3
h = 0.003
term = 16
i = 0.01
func = np.matrix([f(i-3*h),f(i-2*h),f(i-h),f(i),f(i+h),f(i+2*h),f(i+3*h)])/(h**4)
deriv_old = (np.matmul(func,c)/6/math.factorial(term)) * (-1) ** (2)
f = lambda x: np.cos(x)
while tol > 1e-15:
#     h = 0.01/j

    func = np.matrix([f(i-3*h),f(i-2*h),f(i-h),f(i),f(i+h),f(i+2*h),f(i+3*h)])/(h**4)
#     print(func)

    sign = 1
    rem = (term)%4
    if rem == 0:
        sign = 2    
#     print(sign)

    deriv = (np.matmul(func,c)/6/math.factorial(term)) * (-1) ** (sign)
    print(deriv)
    
    tol = abs(deriv_old - deriv)
    print(float(tol))
    deriv_old = deriv
    h += 0.0001*(6+1)

print(h)

[[4.77976905e-14]]
0.0
0.0037


In [78]:
tol = 1e-3
h = 0.0001
term = 15
i = 0.01
func = np.matrix([f(i-3*h),f(i-2*h),f(i-h),f(i),f(i+h),f(i+2*h),f(i+3*h)])/(h**4)
deriv_old = (np.matmul(func,c)/6/math.factorial(term)) * (-1) ** (2)
f = lambda x: np.sin(x)
while tol > 1e-15:
#     h = 0.01/j

    func = np.matrix([f(i-3*h),f(i-2*h),f(i-h),f(i),f(i+h),f(i+2*h),f(i+3*h)])/(h**4)
#     print(func)

    sign = 1
    rem = (term)%4
    if rem == 0:
        sign = 2    
#     print(sign)

    deriv = (np.matmul(func,c)/math.factorial(term)) * (-1) ** (2)
    print(deriv)
    
    tol = abs(deriv_old - deriv)
    print(float(tol))
    deriv_old = deriv
    h += 0.00001*(6+1)

print(h)

[[4.58829824e-12]]
7.290296091001558e-11
[[4.77947733e-13]]
4.1103505058531515e-12
[[1.792304e-13]]
2.9871733327421157e-13
[[9.857672e-14]]
8.065367998403712e-14
[[6.72114e-14]]
3.1365319993792214e-14
[[5.52627067e-14]]
1.1948693330968465e-14
[[5.152874e-14]]
3.733966665927648e-15
[[4.94750583e-14]]
2.0536816662602025e-15
[[4.83548683e-14]]
1.1201899997782951e-15
[[4.73280275e-14]]
1.026840833130098e-15
[[4.69546308e-14]]
3.7339666659276294e-16
0.0008699999999999999
