In [1]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(precision=7)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA
from sympy import * 

In [2]:
# Scale function
def scale(vec_1):
    
    # Test
    v1_scale = np.square(np.linalg.norm(vec_1))
#     print(v1_scale)

    v1 = np.multiply(1/np.sqrt(v1_scale + 1e-15),vec_1)
#     print(v1)
    
    return list(v1)
    
    
def QR(span):
    
    # Setup arrays
    # Original Values
    vector = []
    # Normalized Values
    vec_norm = []

    # Size of array
    row,col = span.shape
    
    # First Column
    v1 = span[:,0]
    vec_1 = v1
    vector.append(vec_1)

    v1 = scale(vec_1)
    vec_norm.append(v1)
    
    # Subsequent Columns

    start = 1
    end = col

    for j in range(start,end):

        # Column
        projection = span[:,j]
        v = span[:,j]

        #Orthonormal vector
        for i in range(len(vec_norm)):
            #projection
            # dot
            proj_dot = np.dot(v,vec_norm[i])/(np.dot(vec_norm[i],vec_norm[i]) + 1e-15)
            proj = np.multiply(proj_dot,vec_norm[i])
            projection = projection - proj

        v_norm = scale(projection)

        vec_norm.append(v_norm)
        
    # Calculate R
    Q = vec_norm
    Q = np.array(Q)
    R = np.dot(Q,span)
    R = np.array(R)

    
    return Q.T,R

def eigenspace(span):
    
    eig_vec = np.eye(span.shape[0])
    X = span.copy()

    for _ in range(100):
        Q,R = QR(X)
        eig_vec = np.dot(eig_vec,Q)
        X = np.dot(R,Q)
        eig_val = np.diag(X)
        
    return eig_val,eig_vec, X


In [3]:
v1 = np.array([[0.6778726],[0.7351785]])
v2 = np.array([[-0.7351785], [0.6778736]])
v1_v2 = np.concatenate([v1,v2])
v1_v2 = v1_v2.reshape(2,2).T

print(v1)
print(v2)
print(v1_v2)

[[0.6778726]
 [0.7351785]]
[[-0.7351785]
 [ 0.6778736]]
[[ 0.6778726 -0.7351785]
 [ 0.7351785  0.6778736]]


In [4]:
# w,v,u = eigenspace(v1_v2)
# print(w)
# print(v)
# print(u)

In [5]:
lamda_1 = 1.284028
lamda_2 = 0.04908323
lamda_sum = lamda_1 + lamda_2
pc1 = lamda_1/lamda_sum
pc2 = lamda_2/lamda_sum

print(pc1)
print(pc2)

0.9631814443570474
0.03681855564295262
