In [1]:
%matplotlib inline
import numpy as np
np.set_printoptions(linewidth=np.inf)
# np.set_printoptions(precision=7)
import matplotlib.pyplot as plt
import math 
import pandas as pd
from numpy import linalg as LA
from sympy import * 

In [2]:
# Scale function
def scale(vec_1):
    
    # Test
    v1_scale = np.square(np.linalg.norm(vec_1))
#     print(v1_scale)

    v1 = np.multiply(1/np.sqrt(v1_scale + 1e-15),vec_1)
#     print(v1)
    
    return list(v1)
    
    
def QR(span):
    
    # Setup arrays
    # Original Values
    vector = []
    # Normalized Values
    vec_norm = []

    # Size of array
    row,col = span.shape
    
    # First Column
    v1 = span[:,0]
    vec_1 = v1
    vector.append(vec_1)

    v1 = scale(vec_1)
    vec_norm.append(v1)
    
    # Subsequent Columns

    start = 1
    end = col

    for j in range(start,end):

        # Column
        projection = span[:,j]
        v = span[:,j]

        #Orthonormal vector
        for i in range(len(vec_norm)):
            #projection
            # dot
            proj_dot = np.dot(v,vec_norm[i])/(np.dot(vec_norm[i],vec_norm[i]) + 1e-15)
            proj = np.multiply(proj_dot,vec_norm[i])
            projection = projection - proj

        v_norm = scale(projection)

        vec_norm.append(v_norm)
        
    # Calculate R
    Q = vec_norm
    Q = np.array(Q)
    R = np.dot(Q,span)
    R = np.array(R)

    
    return Q.T,R

def eigenspace(span):
    
    eig_vec = np.eye(span.shape[0])
    X = span.copy()

    for _ in range(100):
        Q,R = QR(X)
        eig_vec = np.dot(eig_vec,Q)
        X = np.dot(R,Q)
        eig_val = np.diag(X)
        
    return eig_val,eig_vec, X


In [3]:
# A = np.array([[4,4],[-3,3]])
# A = np.array([[2,4],[1,3],[0,0],[0,0]])

row = 6
col = 5
A = np.random.randint(-10,10,size=(row,col))

row,col = A.shape

if col > row:
    np.set_printoptions(precision=0)
    

B = A.copy()

print(A)

[[  0   2  -8   5   8]
 [  6   0 -10  -6   2]
 [  8   4   7   9  -2]
 [  1   2  -9   8   1]
 [ -7   0   6   1   5]
 [ -2   2  -8   7   1]]


In [4]:
A1 = A.dot(A.T)
print(A1)
A2 = np.dot(A.T,A)
print(A2)

[[157  66 -19 124  -3 111]
 [ 66 176 -80  50 -98  28]
 [-19 -80 214  23 -15  -3]
 [124  50  23 151 -48 131]
 [ -3 -98 -15 -48 111 -22]
 [111  28  -3 131 -22 122]]
[[154  30 -39  23 -40]
 [ 30  28 -22  76  12]
 [-39 -22 394 -39 -85]
 [ 23  76 -39 256  30]
 [-40  12 -85  30  99]]


In [5]:
# Eigenvalues
eig_val_A1,eig_vec_A1,x_A1 = eigenspace(A1)
print(eig_val_A1)
print(eig_vec_A1)
print(x_A1)

print('\n')

eig_val_A2,eig_vec_A2,x_A2 = eigenspace(A2)
print(eig_val_A2)
print(eig_vec_A2)
print(x_A2)

print('\n')

V = eig_vec_A2.T
print('V:',V)

[438.13083831 266.62697023 175.14472417  50.48141679   0.61605632   0.        ]
[[ 0.52218951 -0.12224972 -0.30082512 -0.59091958 -0.33139382  0.        ]
 [ 0.40622102  0.48660665  0.43164243 -0.39386791  0.41218729  0.        ]
 [-0.12527443 -0.77672352  0.48256321 -0.32883766  0.19727608  0.        ]
 [ 0.53336841 -0.28623978 -0.02483936  0.29291555 -0.34837975  0.        ]
 [-0.22976874 -0.10893894 -0.66642868 -0.36803345  0.36270971  0.        ]
 [ 0.45752965 -0.22620486 -0.21348916  0.4077987   0.65455654  0.        ]]
[[ 4.38130838e+02 -1.65890334e-14 -1.46944809e-14  3.43411186e-14  2.25549405e-16  0.00000000e+00]
 [ 1.08073497e-20  2.66626970e+02 -1.46780737e-14  1.52802481e-15 -3.84942986e-15  0.00000000e+00]
 [-6.72376511e-29 -5.87737166e-17  1.75144724e+02  1.08434365e-14 -3.62265758e-15  0.00000000e+00]
 [ 3.67061698e-28  1.14097027e-29  6.30804372e-29  5.04814168e+01  6.88110487e-15  0.00000000e+00]
 [ 1.60000267e-28 -1.66607801e-27 -1.16178018e-27  6.68816036e-28  6.1605

In [6]:
#singular values
sigma_A2 = []
eig_val = eig_val_A2
for i in range(len(eig_val)):
    sigma_A2.append(np.sqrt(eig_val[i]))
    
print(sigma_A2)

[20.931575149669587, 16.32871612216575, 13.234225482328531, 7.105027567795113, 0.7848889725421784]


In [7]:
Sigma = np.sqrt(eig_val_A2) * np.eye(len(sigma_A2))
print(Sigma)
# V = [v1,v2]
V = eig_vec_A2
V = np.array(V)
print(V)
print(V.T)

[[20.93157515  0.          0.          0.          0.        ]
 [ 0.         16.32871612  0.          0.          0.        ]
 [ 0.          0.         13.23422548  0.          0.        ]
 [ 0.          0.          0.          7.10502757  0.        ]
 [ 0.          0.          0.          0.          0.78488897]]
[[ 0.12716773  0.14486171  0.87028138 -0.41384167  0.18490226]
 [ 0.12063485  0.26801144  0.06437442 -0.15422338 -0.94111008]
 [-0.90560851  0.34252356 -0.04526033 -0.24527113  0.01855811]
 [ 0.30031364  0.8882322  -0.15947129  0.18000669  0.25104138]
 [ 0.24281791 -0.03010177 -0.45933285 -0.84403192  0.12944804]]
[[ 0.12716773  0.12063485 -0.90560851  0.30031364  0.24281791]
 [ 0.14486171  0.26801144  0.34252356  0.8882322  -0.03010177]
 [ 0.87028138  0.06437442 -0.04526033 -0.15947129 -0.45933285]
 [-0.41384167 -0.15422338 -0.24527113  0.18000669 -0.84403192]
 [ 0.18490226 -0.94111008  0.01855811  0.25104138  0.12944804]]


In [8]:
Sigma_V = Sigma.dot(V.T)
print(Sigma_V)

U = A.dot(np.linalg.pinv(Sigma_V))
print(U)

A = U.dot(Sigma).dot(V.T)
print(A)

print(B)

[[ 2.66182098e+00  2.52507738e+00 -1.89558126e+01  6.28603760e+00  5.08256135e+00]
 [ 2.36540576e+00  4.37628279e+00  5.59297004e+00  1.45036915e+01 -4.91523212e-01]
 [ 1.15175000e+01  8.51945606e-01 -5.98985369e-01 -2.11047899e+00 -6.07891449e+00]
 [-2.94035647e+00 -1.09576139e+00 -1.74265816e+00  1.27895246e+00 -5.99687007e+00]
 [ 1.45127744e-01 -7.38666923e-01  1.45660579e-02  1.97039611e-01  1.01602339e-01]]
[[ 0.52218953  0.12224974 -0.30082514 -0.59091954  0.33139231]
 [ 0.406221   -0.48660667  0.43164246 -0.39386795 -0.41218541]
 [-0.12527444  0.77672351  0.48256323 -0.32883768 -0.19727518]
 [ 0.53336842  0.2862398  -0.02483938  0.29291559  0.34837816]
 [-0.22976876  0.10893892 -0.66642866 -0.36803348 -0.36270805]
 [ 0.45752963  0.22620484 -0.21348912  0.40779863 -0.65455356]]
[[-3.22379478e-15  2.00000000e+00 -8.00000000e+00  5.00000000e+00  8.00000000e+00]
 [ 6.00000000e+00 -2.85300778e-15 -1.00000000e+01 -6.00000000e+00  2.00000000e+00]
 [ 8.00000000e+00  4.00000000e+00  7.00

In [9]:
# # Normalize vectors
# # CV = CV.T
# print(CV)

# row,col = CV.shape

# for i in range(row):
#     CV[i] = CV[i]/(np.linalg.norm(CV[i]) + 1e-15)
    
# print(CV)

In [10]:
# # Solve for U
# print(Sigma)
# U = CV.dot(np.linalg.pinv(Sigma))
# U1 = U
# print(U1)
# # print(V)
# # print(V.T)